"""Curated operational risks in our own words, grounded to course files."""

RISKS = [
    {
        "id": "r-pipeline-as-model",
        "title": "Treating the pipeline as the model",
        "kind": "technical",
        "leading_signal": "Nobody can name tokenizer versus weights when output is wrong.",
        "spot_it_live": "Ask which object lives in GPU RAM.",
        "mitigation": "Draw preprocess, forward, postprocess before shipping.",
        "example": "A fill-mask 'bug' that was a missing [MASK] token.",
        "twin": "pipeline-flow",
        "source_file": "01_llm_intro.ipynb",
    },
    {
        "id": "r-gpu-ram",
        "title": "Host RAM mistaken for GPU RAM",
        "kind": "technical",
        "leading_signal": "Checkpoint loads, then CUDA OOM.",
        "spot_it_live": "Compare nvidia-smi to free -h (do not run them here).",
        "mitigation": "Budget GPU bytes separately; consider GPTQ 13B.",
        "example": "70B FP16 ~135 GB story from notebook 6.",
        "twin": "quantization-memory",
        "source_file": "06_textgen.ipynb",
    },
    {
        "id": "r-concat-embeddings",
        "title": "Concatenating BERT embeddings",
        "kind": "technical",
        "leading_signal": "Hidden size 2304 in a custom fork.",
        "spot_it_live": "Print embedding output shape after the three lookups.",
        "mitigation": "Add in 768-d, then LayerNorm.",
        "example": "Notebook 2 addition formula.",
        "twin": "tokenizer-embeddings",
        "source_file": "02_llm_intake.ipynb",
    },
    {
        "id": "r-extractive-hallucination",
        "title": "Expecting span QA to invent facts",
        "kind": "business",
        "leading_signal": "Support bot cites answers not in the knowledge article.",
        "spot_it_live": "Remove the answer span from context and re-ask.",
        "mitigation": "Use extractive heads only when the answer must be a substring.",
        "example": "SQuAD start/end logits.",
        "twin": "encoder-heads",
        "source_file": "03_encoder_task.ipynb",
    },
    {
        "id": "r-t5-as-chatgpt",
        "title": "Shipping vanilla T5 as a chatbot",
        "kind": "business",
        "leading_signal": "Open instructions collapse into prefix-style noise.",
        "spot_it_live": "Same prompt on t5-large versus flan-t5-large.",
        "mitigation": "Use an instruction-tuned checkpoint or a decoder chat model.",
        "example": "Notebook 4 Flan contrast.",
        "twin": "seq2seq-t5",
        "source_file": "04_seq2seq.ipynb",
    },
    {
        "id": "r-clip-as-captioner",
        "title": "Calling CLIP a captioner",
        "kind": "technical",
        "leading_signal": "Product spec says 'CLIP writes the alt text'.",
        "spot_it_live": "CLIP returns scores, not tokens.",
        "mitigation": "Use BLIP or ViT-GPT2 to generate; CLIP to retrieve.",
        "example": "Notebook 5 dual encoders.",
        "twin": "multimodal",
        "source_file": "05_multimodal.ipynb",
    },
    {
        "id": "r-quant-quality",
        "title": "Assuming 4-bit always wins",
        "kind": "business",
        "leading_signal": "Accuracy drop blamed on 'the GPU'.",
        "spot_it_live": "Compare a golden prompt at 16-bit versus 4-bit on the same machine.",
        "mitigation": "Separate memory constraint from quality constraint.",
        "example": "GPTQ typical-use story.",
        "twin": "quantization-memory",
        "source_file": "06_textgen.ipynb",
    },
    {
        "id": "r-wrong-template",
        "title": "Raw completion on a chat checkpoint",
        "kind": "technical",
        "leading_signal": "Llama-2-chat ignores the user or echoes the system prompt.",
        "spot_it_live": "Check for INST and SYS markers.",
        "mitigation": "Apply the fine-tune template.",
        "example": "Notebook 6 chat format.",
        "twin": "decoder-sampling",
        "source_file": "06_textgen.ipynb",
    },
    {
        "id": "r-stateless-chain",
        "title": "LLMChain used as a conversation",
        "kind": "technical",
        "leading_signal": "Turn two does not know turn one.",
        "spot_it_live": "Log the prompt; history variable empty.",
        "mitigation": "ConversationChain plus history in input_variables.",
        "example": "Notebook 7 gotcha.",
        "twin": "langchain-memory",
        "source_file": "07_stateful_models.ipynb",
    },
    {
        "id": "r-python-repl",
        "title": "Python REPL as a default tool",
        "kind": "security",
        "leading_signal": "Agent can exec arbitrary code.",
        "spot_it_live": "Tool list includes a live interpreter.",
        "mitigation": "Prefer Ask-For-Input or a narrow function.",
        "example": "Notebook 7: bad idea in practice.",
        "twin": "incident-diagnosis",
        "source_file": "07_stateful_models.ipynb",
    },
    {
        "id": "r-rag-vs-agent",
        "title": "Calling every retrieval an agent",
        "kind": "business",
        "leading_signal": "Roadmap says 'agent' but the design is stuff-the-prompt.",
        "spot_it_live": "Is there an event loop that can stop?",
        "mitigation": "Name RAG and agents separately.",
        "example": "Notebook 7 distinction.",
        "twin": "rag-agent",
        "source_file": "07_stateful_models.ipynb",
    },
    {
        "id": "r-toxicity-sign",
        "title": "Flipping the toxicity reward",
        "kind": "security",
        "leading_signal": "Filter keeps the worst comments.",
        "spot_it_live": "Model card: reward equals 1 minus toxicity.",
        "mitigation": "Unit-test 0.9 reward means 0.1 toxicity.",
        "example": "Assessment WARNING.",
        "twin": "assessment-agent",
        "source_file": "08_assessment.ipynb",
    },
    {
        "id": "r-70b-grader",
        "title": "Building against the wrong grader size",
        "kind": "business",
        "leading_signal": "Local 70B never matches the 13B harness.",
        "spot_it_live": "Read 8.1.1 Select Your Model.",
        "mitigation": "TheBloke Llama-2-13B-chat-GPTQ.",
        "example": "Assessment notebook.",
        "twin": "assessment-agent",
        "source_file": "08_assessment.ipynb",
    },
    {
        "id": "r-sim-as-actual",
        "title": "Citing a twin as a GPU measurement",
        "kind": "business",
        "leading_signal": "Slide says 'we measured 24 ms TPOT' from a web slider.",
        "spot_it_live": "Evidence badge is purple SIMULATION.",
        "mitigation": "Import AIPerf as ACTUAL_RUN if you measured.",
        "example": "This academy's evidence model.",
        "twin": "risk-radar",
        "source_file": "01_llm_intro.ipynb",
    },
    {
        "id": "r-missing-license",
        "title": "Missing extras_and_licenses notebook",
        "kind": "business",
        "leading_signal": "Legal asks for the DLI license appendix; it is not in this repo.",
        "spot_it_live": "Search course-materials for extras_and_licenses.",
        "mitigation": "Bring your own license files; do not invent them.",
        "example": "Source inventory missing-assets list.",
        "twin": "risk-radar",
        "source_file": "01_llm_intro.ipynb",
    },
    {
        "id": "r-prompt-injection",
        "title": "Untrusted retrieved text as instructions",
        "kind": "security",
        "leading_signal": "A binder page says 'ignore previous policy'.",
        "spot_it_live": "Retrieved chunks concatenated into the system prompt.",
        "mitigation": "Treat retrieved text as DATA, same as notebooks here.",
        "example": "RAG path in notebook 7.",
        "twin": "rag-agent",
        "source_file": "07_stateful_models.ipynb",
    },
    {
        "id": "r-codegen-overtalk",
        "title": "Code model overgenerates past the function",
        "kind": "technical",
        "leading_signal": "IDE insert keeps writing a second file.",
        "spot_it_live": "No stop sequence after the closing brace.",
        "mitigation": "Stop strings and task-specific models.",
        "example": "CodeGen failure modes.",
        "twin": "decoder-sampling",
        "source_file": "06_textgen.ipynb",
    },
    {
        "id": "r-never-execute",
        "title": "Auto-running notebook shell cells",
        "kind": "security",
        "leading_signal": "A learning site execs nvidia-smi or kubectl from a cell.",
        "spot_it_live": "Safety banner missing on code cells.",
        "mitigation": "Parse as data. Sandbox is a future, explicit feature.",
        "example": "This platform's never_execute flag.",
        "twin": "incident-diagnosis",
        "source_file": "01_llm_intro.ipynb",
    },
]
