"""Source-grounded concept graph for NVIDIA DLI RAD-LLM."""

from __future__ import annotations

CONCEPTS: list[dict] = [
    # --- 01 ---
    dict(id="c-dl-stack", slug="deep-learning-stack", name="Deep learning progression", cluster="fundamentals",
         definition="The course recalls linear models → stacked nonlinear layers → convolution → pretrained backbones (VGG-16/ResNet) as the path into language modeling.",
         school="You started with simple lines, then stacked layers, then reused big pretrained vision nets. Language is the next huge, messy input.",
         engineer="Transfer learning from large pretrained components is presented as the practical way to handle high-dimensional language, analogous to ImageNet backbones.",
         research="The notebook treats language combinatorics as comparable in difficulty to 200×200×3 images (120,000 features) and defers tractability to pretrained LLM ecosystems.",
         notebook_file="01_llm_intro.ipynb", cell_index=5, twin_id="pipeline-flow"),
    dict(id="c-hf", slug="huggingface", name="HuggingFace", cluster="fundamentals",
         definition="Open-source community for accessing, uploading, and using large deep learning models; this course focuses on LLMs.",
         school="HuggingFace is a big library of ready-made language models you can download like apps.",
         engineer="The catalog plus `transformers` is the default intake path for bert-base-uncased and later models.",
         research="HF is treated as infrastructure, not as a paper; licenses are deferred to a missing extras notebook.",
         notebook_file="01_llm_intro.ipynb", cell_index=8, twin_id="pipeline-flow"),
    dict(id="c-transformers", slug="transformers-library", name="transformers library", cluster="fundamentals",
         definition="HuggingFace package supporting most platform language-modeling code; named for the Transformer architecture.",
         school="The Python package that actually loads BERT and friends.",
         engineer="You will live in `transformers` source when pipelines hide too much.",
         research="Name collision: library vs architecture. The course uses both meanings.",
         notebook_file="01_llm_intro.ipynb", cell_index=8, twin_id="pipeline-flow"),
    dict(id="c-pipeline", slug="huggingface-pipeline", name="HuggingFace Pipeline", cluster="fundamentals",
         definition="End-to-end process from human-reasonable input to human-reasonable output, hiding tensor-in/tensor-out.",
         school="Type a sentence, get a filled-in blank. The math stays backstage.",
         engineer="FillMaskPipeline: preprocess (tokenizer) → forward (model) → postprocess (task).",
         research="Pipelines make it easy to forget there is a differentiable model; the course exists to un-forget that.",
         notebook_file="01_llm_intro.ipynb", cell_index=14, twin_id="pipeline-flow"),
    dict(id="c-bert-base", slug="bert-base-uncased", name="bert-base-uncased", cluster="fundamentals",
         definition="Representative HuggingFace encoder used for fill-mask in notebook 1.",
         school="The first LLM you pull: BERT, uncased, fill in [MASK].",
         engineer="Loaded via pipeline('fill-mask', model='bert-base-uncased').",
         research="MLM-pretrained bidirectional encoder; 768-d, 12 layers, 30,522 vocab (notebook 2).",
         notebook_file="01_llm_intro.ipynb", cell_index=9, twin_id="pipeline-flow"),
    dict(id="c-tokenizer", slug="tokenizer", name="Tokenizer", cluster="intake",
         definition="Strategy converting input strings to something usable by the model (tokens / input_ids).",
         school="The translator from English letters to ID numbers the model understands.",
         engineer="preprocess is facilitated by tokenizer; AutoTokenizer / BertTokenizer.",
         research="A token is a symbolic class: word, letter, or substring; ordered sequence of classes.",
         notebook_file="01_llm_intro.ipynb", cell_index=14, twin_id="tokenizer-embeddings"),
    dict(id="c-gpu-ram", slug="gpu-ram", name="GPU RAM vs system memory", cluster="fundamentals",
         definition="Course environment: system memory holds huge models; GPU RAM must hold weights for accelerated inference; budget is 'decent but not infinite'.",
         school="The graphics card has its own memory. Big models need that extra suitcase.",
         engineer="Low GPU RAM constrains accelerated LLMs even if host RAM is large.",
         research="Embarrassingly parallel matmuls make CUDA cores useful for forward/backward.",
         notebook_file="01_llm_intro.ipynb", cell_index=17, twin_id="quantization-memory"),
    # --- 02 ---
    dict(id="c-token", slug="token", name="Token", cluster="intake",
         definition="Symbolic representation, usually a word, letter, or substring; a class from a vocabulary.",
         school="A LEGO brick of language.",
         engineer="input_ids index the vocabulary; encode/decode round-trip includes special tokens.",
         research="NLP as classification over an ordered sequence of discrete classes.",
         notebook_file="02_llm_intake.ipynb", cell_index=5, twin_id="tokenizer-embeddings"),
    dict(id="c-input-ids", slug="input-ids", name="input_ids", cluster="intake",
         definition="IDs of the tokens that make up the sentence; the primary model input the course cares about.",
         school="The list of brick numbers.",
         engineer="Most important input segment for BERT-like models in this course.",
         research="Reasoning target: ordered sequence of tokens.",
         notebook_file="02_llm_intake.ipynb", cell_index=6, twin_id="tokenizer-embeddings"),
    dict(id="c-token-type", slug="token-type-ids", name="token_type_ids", cluster="intake",
         definition="Extra BERT flag: first vs second sentence; part of BERT's training objective; rarely used knowingly in practice.",
         school="A sticker that says 'sentence A' or 'sentence B'.",
         engineer="tokenizer(s1, s2) fills type ids. Type embeddings are a few rows × 768.",
         research="NSP uses this structure; RoBERTa later drops NSP.",
         notebook_file="02_llm_intake.ipynb", cell_index=6, twin_id="tokenizer-embeddings"),
    dict(id="c-attn-mask", slug="attention-mask", name="attention_mask", cluster="intake",
         definition="Regulates what tokens a token can attend to; for BERT often padding; pipelines usually handle it.",
         school="A permission slip for looking at neighbors.",
         engineer="Boolean / additive -inf mask inside attention.",
         research="More critical for decoder causal masks later; encoder padding is the notebook 2 use.",
         notebook_file="02_llm_intake.ipynb", cell_index=6, twin_id="attention-encoder"),
    dict(id="c-word-emb", slug="word-embeddings", name="Word embeddings", cluster="intake",
         definition="Learned 768-d vectors from a 30,522-row table capturing token meaning/usage.",
         school="Each word-brick has a personality vector.",
         engineer="Embedding(30522, 768); lookup by input_id.",
         research="Course investigates cosine vs scaled-dot vs softmax similarity as a prelude to attention.",
         notebook_file="02_llm_intake.ipynb", cell_index=10, twin_id="tokenizer-embeddings"),
    dict(id="c-pos-emb", slug="position-embeddings", name="Position embeddings", cluster="intake",
         definition="Learned 768-d vectors over 512 positions; BERT optimizes them rather than using sinusoids.",
         school="Where the brick sits in the sentence also has a vector.",
         engineer="Embedding(512, 768) indexed by torch.arange(len).",
         research="512 is BERT's practical context; not a hard law of physics—performance degrades beyond.",
         notebook_file="02_llm_intake.ipynb", cell_index=17, twin_id="tokenizer-embeddings"),
    dict(id="c-emb-add", slug="embedding-addition", name="Embedding addition", cluster="intake",
         definition="BERT embed = WordEmbed[token] + PosEmbed[pos] + TypeEmbed[type], then LayerNorm and Dropout.",
         school="Stack the personality, the seat number, and the sentence sticker by adding arrows.",
         engineer="Addition, not concatenation — HuggingFace modeling_bert.py.",
         research="LayerNorm vs BatchNorm: normalize layer outputs; Dropout for co-adaptation.",
         notebook_file="02_llm_intake.ipynb", cell_index=21, twin_id="tokenizer-embeddings"),
    dict(id="c-attention", slug="self-attention", name="Self-attention", cluster="attention",
         definition="Q, K, V from the same sequence; softmax attention weights values. Interface for sequence-level reasoning without a giant dense net over all tokens.",
         school="Each word asks 'who matters?' then borrows those friends' notes.",
         engineer="Softmax(QK^T/√d_k) V. Course writes K/Q notation carefully in the notebook.",
         research="Magnitude and cosine both matter because of scaled softmax; output stays bounded.",
         notebook_file="02_llm_intake.ipynb", cell_index=24, twin_id="attention-encoder"),
    dict(id="c-mha", slug="multi-head-attention", name="Multi-head attention", cluster="attention",
         definition="BERT splits 768 into 12 heads of 64-d, concatenates back.",
         school="Twelve specialists look at the sentence differently, then merge notes.",
         engineer="12 trios × 64 = 768 after concat.",
         research="Allows distributing attention patterns; BertViz visualizes per-head maps.",
         notebook_file="02_llm_intake.ipynb", cell_index=27, twin_id="attention-encoder"),
    dict(id="c-residual", slug="residual-connections", name="Residual connections", cluster="attention",
         definition="Add-backs around transformer blocks to keep token-level information and improve gradient flow.",
         school="A shortcut so the original word doesn't get lost in the committee.",
         engineer="Standard post-norm BERT block with residuals around attention and MLP.",
         research="Course lists residuals as enforcing token boundaries loosely together with per-token MLPs.",
         notebook_file="02_llm_intake.ipynb", cell_index=27, twin_id="attention-encoder"),
    dict(id="c-encoder", slug="transformer-encoder", name="Transformer encoder", cluster="attention",
         definition="n-sequence in, n-sequence out latent sequence; 12 BERT layers with attention + 768→3072→768 MLP.",
         school="A machine that rewrites every brick using the whole sentence, same number of bricks out.",
         engineer="BertEncoder stack; last_hidden_state shape [batch, seq, 768].",
         research="Default utility: semantically rich contextual vectors, not yet a response generator.",
         notebook_file="03_encoder_task.ipynb", cell_index=4, twin_id="encoder-heads"),
    # --- 03 ---
    dict(id="c-mlm", slug="masked-language-modeling", name="Masked language modeling", cluster="encoder-tasks",
         definition="Recover original tokens after [MASK] and random swaps; bidirectional per-token objective.",
         school="Cover a word, guess it from both sides.",
         engineer="BertOnlyMLMHead: dense 768→768 GELU LayerNorm then 768→30522.",
         research="Primary BERT-like objective; postprocess argmaxes the [MASK] row.",
         notebook_file="03_encoder_task.ipynb", cell_index=7, twin_id="encoder-heads"),
    dict(id="c-token-cls", slug="token-classification", name="Token classification", cluster="encoder-tasks",
         definition="Sort each token into classes; mask filling is the variant whose output space is the token vocabulary.",
         school="Label every word: name, place, or blank-to-fill.",
         engineer="Token-level dense head on encoder outputs.",
         research="1-to-1 token conversion or selection tasks.",
         notebook_file="03_encoder_task.ipynb", cell_index=4, twin_id="encoder-heads"),
    dict(id="c-qa-span", slug="span-qa", name="Span / range QA", cluster="encoder-tasks",
         definition="Predict start and end tokens so the answer is a substring of the input.",
         school="Highlight the answer already in the paragraph.",
         engineer="deepset/roberta-base-squad2; qa_outputs Linear(768, 2).",
         research="Stability for public apps; cannot produce conversational novel tokens.",
         notebook_file="03_encoder_task.ipynb", cell_index=7, twin_id="encoder-heads"),
    dict(id="c-nsp", slug="next-sentence-prediction", name="Next-sentence prediction", cluster="encoder-tasks",
         definition="BERT auxiliary task: predict whether sentence B follows A; contested; RoBERTa drops; ALBERT uses SOP.",
         school="Do these two sentences actually go together?",
         engineer="Intended to put long-span logic in CLS.",
         research="Course: MLM is central; NSP is optional/contested.",
         notebook_file="03_encoder_task.ipynb", cell_index=11, twin_id="encoder-heads"),
    dict(id="c-seq-cls", slug="sequence-classification", name="Sequence / text classification", cluster="encoder-tasks",
         definition="Take a specific output position (0th/CLS) through dense layers to a label space.",
         school="One mood sticker for the whole paragraph.",
         engineer="SamLowe/roberta-base-go_emotions; RobertaClassificationHead 768→768→28.",
         research="RoBERTa still classifies well without NSP; internet-scale training encodes passage relations.",
         notebook_file="03_encoder_task.ipynb", cell_index=11, twin_id="encoder-heads"),
    dict(id="c-zeroshot", slug="zero-shot-classification", name="Zero-shot classification", cluster="encoder-tasks",
         definition="Predict labels the model was not specifically trained for by querying multiple times (e.g. NLI).",
         school="Ask 'is this about sports?' then 'is this about cooking?' without retraining.",
         engineer="facebook/bart-large-mnli; MultiNLI entailment per class.",
         research="Zero-shot vs few-shot defined in notebook 3. Multi-query breaks n→1.",
         notebook_file="03_encoder_task.ipynb", cell_index=17, twin_id="encoder-heads"),
    # --- 04 ---
    dict(id="c-seq2seq", slug="seq2seq", name="Sequence-to-sequence", cluster="seq2seq",
         definition="Map an input sequence to an output sequence of possibly different length, e.g. translation.",
         school="English in, French out — not the same number of bricks.",
         engineer="Encoder-only BERT cannot do this naturally; needs a decoder.",
         research="Course contrasts autoencoder 'insight' vs LM 'response sequence'.",
         notebook_file="04_seq2seq.ipynb", cell_index=2, twin_id="seq2seq-t5"),
    dict(id="c-decoder", slug="decoder", name="Decoder (autoregressive)", cluster="seq2seq",
         definition="Generates the next token given context; start token then tokens until </s>.",
         school="Writes the next word, then the next, until it says stop.",
         engineer="Not actually 'just an encoder'; details out of course scope.",
         research="past_key_values caches prior K/V so the decoder can take one new token per step.",
         notebook_file="04_seq2seq.ipynb", cell_index=12, twin_id="seq2seq-t5"),
    dict(id="c-cross-attn", slug="cross-attention", name="Cross-attention", cluster="seq2seq",
         definition="Queries from decoder, keys/values from encoder; n×m interface injecting context.",
         school="The writer keeps glancing at the original paragraph.",
         engineer="If K/V are m from encoder and Q is n from decoder, attn is n×m.",
         research="Same math as self-attention; source of multimodal conditioning later.",
         notebook_file="04_seq2seq.ipynb", cell_index=12, twin_id="seq2seq-t5"),
    dict(id="c-t5", slug="t5", name="T5", cluster="seq2seq",
         definition="Text-to-text transformer; prefixes like 'translate English to German:'; t5-base ≈ 222,903,552 params.",
         school="One model that does many homework types if you label the assignment.",
         engineer="pipeline translation_en_to_fr or text2text-generation; encoder called once.",
         research="Finite task set; larger T5 does not fix arbitrary instructions — need Flan.",
         notebook_file="04_seq2seq.ipynb", cell_index=4, twin_id="seq2seq-t5"),
    dict(id="c-flan", slug="flan-t5", name="Flan-T5", cluster="seq2seq",
         definition="Instruction-finetuned T5 that follows natural language instructions via in-context learning.",
         school="T5 that actually listens when you talk like a person.",
         engineer="google/flan-t5-large text2text-generation.",
         research="Scaling Instruction-Finetuned Language Models; prompt engineering becomes viable.",
         notebook_file="04_seq2seq.ipynb", cell_index=25, twin_id="seq2seq-t5"),
    dict(id="c-icl", slug="in-context-learning", name="In-context learning", cluster="seq2seq",
         definition="Adapt to new tasks from the prompt alone because of instruction-heavy training.",
         school="Showing examples in the question, not retraining.",
         engineer="Emergent in Flan-T5 relative to T5-large on open instructions.",
         research="Not guaranteed for letter-level unnatural tasks (pig latin).",
         notebook_file="04_seq2seq.ipynb", cell_index=28, twin_id="seq2seq-t5"),
    dict(id="c-prompt-eng", slug="prompt-engineering", name="Prompt engineering", cluster="seq2seq",
         definition="Choosing inputs (format, few-shot, iteration, priming) to get better behavior from a frozen model.",
         school="Wording the exam question so the student shows what they know.",
         engineer="Format-abiding, few-shot, trial-and-error, decoder priming.",
         research="Per-model; some cannot deviate enough for a use case.",
         notebook_file="04_seq2seq.ipynb", cell_index=28, twin_id="seq2seq-t5"),
    dict(id="c-hallucination", slug="hallucination", name="Hallucination", cluster="seq2seq",
         definition="Model emits ungrounded personal facts ('what is my name?') rather than abstaining.",
         school="Making up an answer instead of saying 'I don't know'.",
         engineer="Notebook 4 task: ask unknown personal facts; try honesty prompts.",
         research="Course does not claim a complete fix; prompting can reduce but not eliminate.",
         notebook_file="04_seq2seq.ipynb", cell_index=34, twin_id="seq2seq-t5"),
    # --- 05 ---
    dict(id="c-modality", slug="modality", name="Modality", cluster="multimodal",
         definition="Distinct sensory data type with its own rules: language (ordered tokens), images (2D pixels), audio (time series).",
         school="Eyes, ears, and words are different kinds of stuff.",
         engineer="Convolution for spatial locality; transformers for ordered sequences.",
         research="Attention is not limited to words — it is a sequence interface.",
         notebook_file="05_multimodal.ipynb", cell_index=3, twin_id="multimodal"),
    dict(id="c-whisper", slug="whisper", name="Whisper ASR", cluster="multimodal",
         definition="Audio → log-mel spectrogram windows → encoder sequence → decoder via cross-attention. whisper-base ~73M; large-v2 1.55B.",
         school="Turns sound pictures into sentences.",
         engineer="pipeline automatic-speech-recognition; base faster, large-v2 better multilingual.",
         research="Domain losses/tokenizers largely out of course scope; paper recommended.",
         notebook_file="05_multimodal.ipynb", cell_index=6, twin_id="multimodal"),
    dict(id="c-vit", slug="vision-transformer", name="Vision Transformer", cluster="multimodal",
         definition="Image patches as tokens (An Image is Worth 16x16 Words).",
         school="Cut the photo into stamps, read the stamps like words.",
         engineer="Pairs with a language decoder for captioning.",
         research="nlpconnect/vit-gpt2-image-captioning: top-downloaded but course finds it simplistic.",
         notebook_file="05_multimodal.ipynb", cell_index=18, twin_id="multimodal"),
    dict(id="c-blip", slug="blip", name="BLIP captioning", cluster="multimodal",
         definition="Salesforce BLIP: stronger captioning; two encoder layers + specialized pretraining; supports conditional prefixes.",
         school="A better photo-describer that can start with 'I love cats'.",
         engineer="Salesforce/blip-image-captioning-large; BlipProcessor + BlipForConditionalGeneration.",
         research="Used again in assessment for image links.",
         notebook_file="05_multimodal.ipynb", cell_index=25, twin_id="multimodal"),
    dict(id="c-clip", slug="clip", name="CLIP", cluster="multimodal",
         definition="Contrastive language-image pretraining: dual encoders, related pairs agree in embedding space.",
         school="Train a picture brain and a sentence brain to point at the same idea.",
         engineer="openai/clip-vit-base-patch32; get_text_features / get_image_features; softmax similarity.",
         research="Enables retrieval, text-conditioning, and zero-shot image classification.",
         notebook_file="05_multimodal.ipynb", cell_index=35, twin_id="multimodal"),
    # --- 06 ---
    dict(id="c-decoder-only", slug="decoder-only", name="Decoder-only models", cluster="decoder",
         definition="Drop the encoder when context and generation share a vocabulary; feed the passage into the decoder (GPT family).",
         school="One writer that both reads the prompt and continues it.",
         engineer="Loses bidirectional cross-attention supervision; anything in the input can be a command.",
         research="GPT-2 insufficient for unrestricted NLG in the course's judgment.",
         notebook_file="06_textgen.ipynb", cell_index=3, twin_id="decoder-sampling"),
    dict(id="c-codegen", slug="codegen", name="CodeGen", cluster="decoder",
         definition="Salesforce decoder trained on BigPython; tokenizer more granular; 350M-mono used for fibonacci completion.",
         school="An autocomplete for Python that sometimes writes extra junk.",
         engineer="Overgenerate, misinterpret, assume externals, go off track.",
         research="Larger CodeGen 2.5 7B not loaded (compute). Copilot is a multi-model API, not one LLM.",
         notebook_file="06_textgen.ipynb", cell_index=16, twin_id="decoder-sampling"),
    dict(id="c-llama2", slug="llama-2-chat", name="Llama-2 chat", cluster="decoder",
         definition="Open Meta chat models 7B/13B/70B; course uses TheBloke GPTQ. Chat format <s>[INST]<<SYS>>.",
         school="A talkative open model you can run yourself if you shrink it.",
         engineer="Must use the fine-tuned template; raw completion is the wrong interface.",
         research="SFT + human-feedback ranking; ChatGPT internals are not accessible — contrast.",
         notebook_file="06_textgen.ipynb", cell_index=25, twin_id="decoder-sampling"),
    dict(id="c-quant", slug="quantization", name="Quantization", cluster="decoder",
         definition="Map high-precision weights to a smaller numeric set to save memory/compute, usually shifting quality.",
         school="Write the recipe with fewer decimal places so it fits in a smaller notebook.",
         engineer="bitsandbytes load_in_8bit/4bit vs GPTQ (needs unquantized forward; AutoGPTQ/Optimum).",
         research="70B ~135GB; int8 ~69GB and conversion retains original; A100 vs A10/T4 notes.",
         notebook_file="06_textgen.ipynb", cell_index=19, twin_id="quantization-memory"),
    dict(id="c-sft", slug="instruction-finetuning", name="Instruction / SFT", cluster="decoder",
         definition="Fine-tune on formatted synthetic dialog so the model respects roles and templates.",
         school="Practice tests that always use the same worksheet layout.",
         engineer="Llama-2 chat SFT then reward-model ranking.",
         research="Generation priming, few-shot, eos_token_id used to constrain outputs in tasks.",
         notebook_file="06_textgen.ipynb", cell_index=26, twin_id="decoder-sampling"),
    # --- 07 ---
    dict(id="c-orchestrate", slug="llm-orchestration", name="LLM orchestration", cluster="stateful",
         definition="Libraries that organize one or more LLMs to solve real tasks: chat, planning, API calls.",
         school="A stage manager for the actor (the LLM).",
         engineer="LangChain is the course's example; originally GPT-API-centric.",
         research="Local models may not match default chain assumptions.",
         notebook_file="07_stateful_models.ipynb", cell_index=4, twin_id="langchain-memory"),
    dict(id="c-chain", slug="langchain-chain", name="LangChain Chain", cluster="stateful",
         definition="Dict-in dict-out module composable like nn.Module; TransformChain, SequentialChain, LLMChain.",
         school="LEGO blocks that pass dictionaries instead of tensors.",
         engineer="LLMChain = prompt + LLM with preprocess/postprocess mental model.",
         research="_call / _acall customization points in source.",
         notebook_file="07_stateful_models.ipynb", cell_index=7, twin_id="langchain-memory"),
    dict(id="c-memory", slug="conversation-memory", name="Conversation memory", cluster="stateful",
         definition="State injected as history; buffer, summary, KG, vector retriever variants.",
         school="A notepad so the bot remembers your name.",
         engineer="ConversationChain + ConversationBuffer; partials gotcha with input_variables.",
         research="Context limit forces lossy summaries; faithfulness vs length tradeoff.",
         notebook_file="07_stateful_models.ipynb", cell_index=27, twin_id="langchain-memory"),
    dict(id="c-rag", slug="rag", name="Retrieval-augmented generation", cluster="stateful",
         definition="Augment generation with retrieved environment text (e.g. vector similarity lookup).",
         school="Open the textbook, then answer.",
         engineer="Always-on retrieval vs agent-chosen tools.",
         research="LlamaIndex deferred to extras / later courses.",
         notebook_file="07_stateful_models.ipynb", cell_index=39, twin_id="rag-agent"),
    dict(id="c-agent", slug="llm-agent", name="Agent", cluster="stateful",
         definition="LLM system(s) in an event loop using tools until stop; ReAct/MRKL inspiration.",
         school="Think, use a tool, look, repeat, then answer.",
         engineer="ZeroShotAgent / initialize_agent zero-shot-react-description; scratchpad.",
         research="Precise: event loop accumulating context. Dialog-spanning loop = assessment.",
         notebook_file="07_stateful_models.ipynb", cell_index=39, twin_id="rag-agent"),
    dict(id="c-tools", slug="agent-tools", name="Tools", cluster="stateful",
         definition="Utilities with name, description, func; AutoTool recipe; Python REPL is powerful and dangerous.",
         school="Buttons the agent is allowed to press.",
         engineer="Ask-For-Input Tool wraps the user. exec() REPL is demo-only.",
         research="Course warns general Python access is a bad idea in practice.",
         notebook_file="07_stateful_models.ipynb", cell_index=43, twin_id="rag-agent"),
    dict(id="c-react", slug="react-mrkl", name="ReAct / MRKL", cluster="stateful",
         definition="Reasoning + Acting; Modular Reasoning, Knowledge and Language — endow options and let the model choose steps.",
         school="Think out loud, then act, then think again.",
         engineer="Prompt format Thought/Action/Action-Input/Observation/Final Answer.",
         research="Works better with examples or finetuning; Llama-2 may fail the default template.",
         notebook_file="07_stateful_models.ipynb", cell_index=44, twin_id="rag-agent"),
    # --- 08 ---
    dict(id="c-assess", slug="assessment-agent", name="Assessment custom agent", cluster="assessment",
         definition="MyAgent on BaseSingleActionAgent; pass ≥3/5: memory, image, code fences, toxicity, emotion.",
         school="Build a chatbot that remembers you, can look at a picture, and notices mood.",
         engineer="plan() uses intermediate_steps; Ask-For-Input Tool; SetParams for gen kwargs.",
         research="ToxicityModel returns reward = 1 - toxicity. Assessment script uses 13B GPTQ.",
         notebook_file="08_assessment.ipynb", cell_index=22, twin_id="assessment-agent"),
    dict(id="c-toxicity-reward", slug="toxicity-reward", name="Inverted toxicity reward", cluster="assessment",
         definition="nicholasKluge/ToxicityModel returns reward where reward = 1 - toxicity.",
         school="A high score means nicer text, not more toxic.",
         engineer="Do not treat the raw logit as toxicity without inversion.",
         research="Useful for guardrails / human handoff — course lists product uses.",
         notebook_file="08_assessment.ipynb", cell_index=23, twin_id="assessment-agent"),
]

EDGES: list[tuple[str, str, str]] = [
    ("c-hf", "c-transformers", "DEPENDS_ON"),
    ("c-transformers", "c-pipeline", "IMPLEMENTED_IN"),
    ("c-pipeline", "c-tokenizer", "PART_OF"),
    ("c-pipeline", "c-bert-base", "IMPLEMENTED_IN"),
    ("c-tokenizer", "c-token", "PART_OF"),
    ("c-token", "c-input-ids", "IMPLEMENTED_IN"),
    ("c-input-ids", "c-word-emb", "DEPENDS_ON"),
    ("c-pos-emb", "c-emb-add", "PART_OF"),
    ("c-word-emb", "c-emb-add", "PART_OF"),
    ("c-token-type", "c-emb-add", "PART_OF"),
    ("c-emb-add", "c-attention", "PREREQUISITE_OF"),
    ("c-attention", "c-mha", "PART_OF"),
    ("c-attention", "c-encoder", "PART_OF"),
    ("c-residual", "c-encoder", "OPTIMIZES"),
    ("c-encoder", "c-mlm", "PREREQUISITE_OF"),
    ("c-mlm", "c-token-cls", "PART_OF"),
    ("c-encoder", "c-qa-span", "PREREQUISITE_OF"),
    ("c-encoder", "c-seq-cls", "PREREQUISITE_OF"),
    ("c-nsp", "c-seq-cls", "OPTIMIZES"),
    ("c-seq-cls", "c-zeroshot", "COMPARES_WITH"),
    ("c-zeroshot", "c-seq2seq", "PREREQUISITE_OF"),
    ("c-encoder", "c-seq2seq", "COMPARES_WITH"),
    ("c-decoder", "c-seq2seq", "PART_OF"),
    ("c-cross-attn", "c-t5", "PART_OF"),
    ("c-t5", "c-flan", "PREREQUISITE_OF"),
    ("c-flan", "c-icl", "INCREASES"),
    ("c-icl", "c-prompt-eng", "IMPLEMENTED_IN"),
    ("c-cross-attn", "c-whisper", "IMPLEMENTED_IN"),
    ("c-cross-attn", "c-vit", "IMPLEMENTED_IN"),
    ("c-vit", "c-blip", "COMPARES_WITH"),
    ("c-clip", "c-blip", "OPTIMIZES"),
    ("c-decoder", "c-decoder-only", "PART_OF"),
    ("c-decoder-only", "c-codegen", "IMPLEMENTED_IN"),
    ("c-decoder-only", "c-llama2", "IMPLEMENTED_IN"),
    ("c-quant", "c-llama2", "OPTIMIZES"),
    ("c-sft", "c-llama2", "OPTIMIZES"),
    ("c-llama2", "c-orchestrate", "PREREQUISITE_OF"),
    ("c-orchestrate", "c-chain", "IMPLEMENTED_IN"),
    ("c-chain", "c-memory", "PART_OF"),
    ("c-memory", "c-rag", "COMPARES_WITH"),
    ("c-rag", "c-agent", "COMPARES_WITH"),
    ("c-agent", "c-tools", "DEPENDS_ON"),
    ("c-react", "c-agent", "IMPLEMENTED_IN"),
    ("c-agent", "c-assess", "PREREQUISITE_OF"),
    ("c-blip", "c-assess", "EVIDENCED_BY"),
    ("c-toxicity-reward", "c-assess", "PART_OF"),
    ("c-qa-span", "c-seq-cls", "COMPARES_WITH"),
    ("c-t5", "c-decoder-only", "COMPARES_WITH"),
    ("c-hallucination", "c-prompt-eng", "DIAGNOSED_BY"),
    ("c-attn-mask", "c-attention", "CONTROLS"),
]
