"""Source-grounded concept graph for NVIDIA DLI RAD-LLM."""

from __future__ import annotations

CONCEPTS: list[dict] = [
    # --- 01 ---
    dict(id="c-dl-stack", slug="deep-learning-stack", name="Deep learning progression", cluster="fundamentals",
         definition="The course recalls linear models → stacked nonlinear layers → convolution → pretrained backbones (VGG-16/ResNet) as the path into language modeling.",
         school="You started with simple lines, then stacked layers, then reused big pretrained vision nets. Language is the next huge, messy input.",
         engineer="Transfer learning from large pretrained components is presented as the practical way to handle high-dimensional language, analogous to ImageNet backbones.",
         research="The notebook treats language combinatorics as comparable in difficulty to 200×200×3 images (120,000 features) and defers tractability to pretrained LLM ecosystems.",
         notebook_file="01_llm_intro.ipynb", cell_index=5, twin_id="pipeline-flow"),
    dict(id="c-hf", slug="huggingface", name="HuggingFace", cluster="fundamentals",
         definition="Open-source community for accessing, uploading, and using large deep learning models; this course focuses on LLMs.",
         school="HuggingFace is a big library of ready-made language models you can download like apps.",
         engineer="The catalog plus `transformers` is the default intake path for bert-base-uncased and later models.",
         research="HF is treated as infrastructure, not as a paper; licenses are deferred to a missing extras notebook.",
         notebook_file="01_llm_intro.ipynb", cell_index=8, twin_id="pipeline-flow"),
    dict(id="c-transformers", slug="transformers-library", name="transformers library", cluster="fundamentals",
         definition="HuggingFace package supporting most platform language-modeling code; named for the Transformer architecture.",
         school="The Python package that actually loads BERT and friends.",
         engineer="You will live in `transformers` source when pipelines hide too much.",
         research="Name collision: library vs architecture. The course uses both meanings.",
         notebook_file="01_llm_intro.ipynb", cell_index=8, twin_id="pipeline-flow"),
    dict(id="c-pipeline", slug="huggingface-pipeline", name="HuggingFace Pipeline", cluster="fundamentals",
         definition="End-to-end process from human-reasonable input to human-reasonable output, hiding tensor-in/tensor-out.",
         school="Type a sentence, get a filled-in blank. The math stays backstage.",
         engineer="FillMaskPipeline: preprocess (tokenizer) → forward (model) → postprocess (task).",
         research="Pipelines make it easy to forget there is a differentiable model; the course exists to un-forget that.",
         notebook_file="01_llm_intro.ipynb", cell_index=14, twin_id="pipeline-flow"),
    dict(id="c-bert-base", slug="bert-base-uncased", name="bert-base-uncased", cluster="fundamentals",
         definition="Representative HuggingFace encoder used for fill-mask in notebook 1.",
         school="The first LLM you pull: BERT, uncased, fill in [MASK].",
         engineer="Loaded via pipeline('fill-mask', model='bert-base-uncased').",
         research="MLM-pretrained bidirectional encoder; 768-d, 12 layers, 30,522 vocab (notebook 2).",
         notebook_file="01_llm_intro.ipynb", cell_index=9, twin_id="pipeline-flow"),
    dict(id="c-tokenizer", slug="tokenizer", name="Tokenizer", cluster="intake",
         definition="Strategy converting input strings to something usable by the model (tokens / input_ids).",
         school="The translator from English letters to ID numbers the model understands.",
         engineer="preprocess is facilitated by tokenizer; AutoTokenizer / BertTokenizer.",
         research="A token is a symbolic class: word, letter, or substring; ordered sequence of classes.",
         notebook_file="01_llm_intro.ipynb", cell_index=14, twin_id="tokenizer-embeddings"),
    dict(id="c-gpu-ram", slug="gpu-ram", name="GPU RAM vs system memory", cluster="fundamentals",
         definition="Course environment: system memory holds huge models; GPU RAM must hold weights for accelerated inference; budget is 'decent but not infinite'.",
         school="The graphics card has its own memory. Big models need that extra suitcase.",
         engineer="Low GPU RAM constrains accelerated LLMs even if host RAM is large.",
         research="Embarrassingly parallel matmuls make CUDA cores useful for forward/backward.",
         notebook_file="01_llm_intro.ipynb", cell_index=17, twin_id="quantization-memory"),
    # --- 02 ---
    dict(id="c-token", slug="token", name="Token", cluster="intake",
         definition="Symbolic representation, usually a word, letter, or substring; a class from a vocabulary.",
         school="A LEGO brick of language.",
         engineer="input_ids index the vocabulary; encode/decode round-trip includes special tokens.",
         research="NLP as classification over an ordered sequence of discrete classes.",
         notebook_file="02_llm_intake.ipynb", cell_index=5, twin_id="tokenizer-embeddings"),
    dict(id="c-input-ids", slug="input-ids", name="input_ids", cluster="intake",
         definition="IDs of the tokens that make up the sentence; the primary model input the course cares about.",
         school="The list of brick numbers.",
         engineer="Most important input segment for BERT-like models in this course.",
         research="Reasoning target: ordered sequence of tokens.",
         notebook_file="02_llm_intake.ipynb", cell_index=6, twin_id="tokenizer-embeddings"),
    dict(id="c-token-type", slug="token-type-ids", name="token_type_ids", cluster="intake",
         definition="Extra BERT flag: first vs second sentence; part of BERT's training objective; rarely used knowingly in practice.",
         school="A sticker that says 'sentence A' or 'sentence B'.",
         engineer="tokenizer(s1, s2) fills type ids. Type embeddings are a few rows × 768.",
         research="NSP uses this structure; RoBERTa later drops NSP.",
         notebook_file="02_llm_intake.ipynb", cell_index=6, twin_id="tokenizer-embeddings"),
    dict(id="c-attn-mask", slug="attention-mask", name="attention_mask", cluster="intake",
         definition="Regulates what tokens a token can attend to; for BERT often padding; pipelines usually handle it.",
         school="A permission slip for looking at neighbors.",
         engineer="Boolean / additive -inf mask inside attention.",
         research="More critical for decoder causal masks later; encoder padding is the notebook 2 use.",
         notebook_file="02_llm_intake.ipynb", cell_index=6, twin_id="attention-encoder"),
    dict(id="c-word-emb", slug="word-embeddings", name="Word embeddings", cluster="intake",
         definition="Learned 768-d vectors from a 30,522-row table capturing token meaning/usage.",
         school="Each word-brick has a personality vector.",
         engineer="Embedding(30522, 768); lookup by input_id.",
         research="Course investigates cosine vs scaled-dot vs softmax similarity as a prelude to attention.",
         notebook_file="02_llm_intake.ipynb", cell_index=10, twin_id="tokenizer-embeddings"),
    dict(id="c-pos-emb", slug="position-embeddings", name="Position embeddings", cluster="intake",
         definition="Learned 768-d vectors over 512 positions; BERT optimizes them rather than using sinusoids.",
         school="Where the brick sits in the sentence also has a vector.",
         engineer="Embedding(512, 768) indexed by torch.arange(len).",
         research="512 is BERT's practical context; not a hard law of physics—performance degrades beyond.",
         notebook_file="02_llm_intake.ipynb", cell_index=17, twin_id="tokenizer-embeddings"),
    dict(id="c-emb-add", slug="embedding-addition", name="Embedding addition", cluster="intake",
         definition="BERT embed = WordEmbed[token] + PosEmbed[pos] + TypeEmbed[type], then LayerNorm and Dropout.",
         school="Stack the personality, the seat number, and the sentence sticker by adding arrows.",
         engineer="Addition, not concatenation — HuggingFace modeling_bert.py.",
         research="LayerNorm vs BatchNorm: normalize layer outputs; Dropout for co-adaptation.",
         notebook_file="02_llm_intake.ipynb", cell_index=21, twin_id="tokenizer-embeddings"),
    dict(id="c-attention", slug="self-attention", name="Self-attention", cluster="attention",
         definition="Q, K, V from the same sequence; softmax attention weights values. Interface for sequence-level reasoning without a giant dense net over all tokens.",
         school="Each word asks 'who matters?' then borrows those friends' notes.",
         engineer="Softmax(QK^T/√d_k) V. Course writes K/Q notation carefully in the notebook.",
         research="Magnitude and cosine both matter because of scaled softmax; output stays bounded.",
         notebook_file="02_llm_intake.ipynb", cell_index=24, twin_id="attention-encoder"),
    dict(id="c-mha", slug="multi-head-attention", name="Multi-head attention", cluster="attention",
         definition="BERT splits 768 into 12 heads of 64-d, concatenates back.",
         school="Twelve specialists look at the sentence differently, then merge notes.",
         engineer="12 trios × 64 = 768 after concat.",
         research="Allows distributing attention patterns; BertViz visualizes per-head maps.",
         notebook_file="02_llm_intake.ipynb", cell_index=27, twin_id="attention-encoder"),
    dict(id="c-residual", slug="residual-connections", name="Residual connections", cluster="attention",
         definition="Add-backs around transformer blocks to keep token-level information and improve gradient flow.",
         school="A shortcut so the original word doesn't get lost in the committee.",
         engineer="Standard post-norm BERT block with residuals around attention and MLP.",
         research="Course lists residuals as enforcing token boundaries loosely together with per-token MLPs.",
         notebook_file="02_llm_intake.ipynb", cell_index=27, twin_id="attention-encoder"),
    dict(id="c-encoder", slug="transformer-encoder", name="Transformer encoder", cluster="attention",
         definition="n-sequence in, n-sequence out latent sequence; 12 BERT layers with attention + 768→3072→768 MLP.",
         school="A machine that rewrites every brick using the whole sentence, same number of bricks out.",
         engineer="BertEncoder stack; last_hidden_state shape [batch, seq, 768].",
         research="Default utility: semantically rich contextual vectors, not yet a response generator.",
         notebook_file="03_encoder_task.ipynb", cell_index=4, twin_id="encoder-heads"),
    # --- 03 ---
    dict(id="c-mlm", slug="masked-language-modeling", name="Masked language modeling", cluster="encoder-tasks",
         definition="Recover original tokens after [MASK] and random swaps; bidirectional per-token objective.",
         school="Cover a word, guess it from both sides.",
         engineer="BertOnlyMLMHead: dense 768→768 GELU LayerNorm then 768→30522.",
         research="Primary BERT-like objective; postprocess argmaxes the [MASK] row.",
         notebook_file="03_encoder_task.ipynb", cell_index=7, twin_id="encoder-heads"),
    dict(id="c-token-cls", slug="token-classification", name="Token classification", cluster="encoder-tasks",
         definition="Sort each token into classes; mask filling is the variant whose output space is the token vocabulary.",
         school="Label every word: name, place, or blank-to-fill.",
         engineer="Token-level dense head on encoder outputs.",
         research="1-to-1 token conversion or selection tasks.",
         notebook_file="03_encoder_task.ipynb", cell_index=4, twin_id="encoder-heads"),
    dict(id="c-qa-span", slug="span-qa", name="Span / range QA", cluster="encoder-tasks",
         definition="Predict start and end tokens so the answer is a substring of the input.",
         school="Highlight the answer already in the paragraph.",
         engineer="deepset/roberta-base-squad2; qa_outputs Linear(768, 2).",
         research="Stability for public apps; cannot produce conversational novel tokens.",
         notebook_file="03_encoder_task.ipynb", cell_index=7, twin_id="encoder-heads"),
    dict(id="c-nsp", slug="next-sentence-prediction", name="Next-sentence prediction", cluster="encoder-tasks",
         definition="BERT auxiliary task: predict whether sentence B follows A; contested; RoBERTa drops; ALBERT uses SOP.",
         school="Do these two sentences actually go together?",
         engineer="Intended to put long-span logic in CLS.",
         research="Course: MLM is central; NSP is optional/contested.",
         notebook_file="03_encoder_task.ipynb", cell_index=11, twin_id="encoder-heads"),
    dict(id="c-seq-cls", slug="sequence-classification", name="Sequence / text classification", cluster="encoder-tasks",
         definition="Take a specific output position (0th/CLS) through dense layers to a label space.",
         school="One mood sticker for the whole paragraph.",
         engineer="SamLowe/roberta-base-go_emotions; RobertaClassificationHead 768→768→28.",
         research="RoBERTa still classifies well without NSP; internet-scale training encodes passage relations.",
         notebook_file="03_encoder_task.ipynb", cell_index=11, twin_id="encoder-heads"),
    dict(id="c-zeroshot", slug="zero-shot-classification", name="Zero-shot classification", cluster="encoder-tasks",
         definition="Predict labels the model was not specifically trained for by querying multiple times (e.g. NLI).",
         school="Ask 'is this about sports?' then 'is this about cooking?' without retraining.",
         engineer="facebook/bart-large-mnli; MultiNLI entailment per class.",
         research="Zero-shot vs few-shot defined in notebook 3. Multi-query breaks n→1.",
         notebook_file="03_encoder_task.ipynb", cell_index=17, twin_id="encoder-heads"),
    # --- 04 ---
    dict(id="c-seq2seq", slug="seq2seq", name="Sequence-to-sequence", cluster="seq2seq",
         definition="Map an input sequence to an output sequence of possibly different length, e.g. translation.",
         school="English in, French out — not the same number of bricks.",
         engineer="Encoder-only BERT cannot do this naturally; needs a decoder.",
         research="Course contrasts autoencoder 'insight' vs LM 'response sequence'.",
         notebook_file="04_seq2seq.ipynb", cell_index=2, twin_id="seq2seq-t5"),
    dict(id="c-decoder", slug="decoder", name="Decoder (autoregressive)", cluster="seq2seq",
         definition="Generates the next token given context; start token then tokens until </s>.",
         school="Writes the next word, then the next, until it says stop.",
         engineer="Not actually 'just an encoder'; details out of course scope.",
         research="past_key_values caches prior K/V so the decoder can take one new token per step.",
         notebook_file="04_seq2seq.ipynb", cell_index=12, twin_id="seq2seq-t5"),
    dict(id="c-cross-attn", slug="cross-attention", name="Cross-attention", cluster="seq2seq",
         definition="Queries from decoder, keys/values from encoder; n×m interface injecting context.",
         school="The writer keeps glancing at the original paragraph.",
         engineer="If K/V are m from encoder and Q is n from decoder, attn is n×m.",
         research="Same math as self-attention; source of multimodal conditioning later.",
         notebook_file="04_seq2seq.ipynb", cell_index=12, twin_id="seq2seq-t5"),
    dict(id="c-t5", slug="t5", name="T5", cluster="seq2seq",
         definition="Text-to-text transformer; prefixes like 'translate English to German:'; t5-base ≈ 222,903,552 params.",
         school="One model that does many homework types if you label the assignment.",
         engineer="pipeline translation_en_to_fr or text2text-generation; encoder called once.",
         research="Finite task set; larger T5 does not fix arbitrary instructions — need Flan.",
         notebook_file="04_seq2seq.ipynb", cell_index=4, twin_id="seq2seq-t5"),
    dict(id="c-flan", slug="flan-t5", name="Flan-T5", cluster="seq2seq",
         definition="Instruction-finetuned T5 that follows natural language instructions via in-context learning.",
         school="T5 that actually listens when you talk like a person.",
         engineer="google/flan-t5-large text2text-generation.",
         research="Scaling Instruction-Finetuned Language Models; prompt engineering becomes viable.",
         notebook_file="04_seq2seq.ipynb", cell_index=25, twin_id="seq2seq-t5"),
    dict(id="c-icl", slug="in-context-learning", name="In-context learning", cluster="seq2seq",
         definition="Adapt to new tasks from the prompt alone because of instruction-heavy training.",
         school="Showing examples in the question, not retraining.",
         engineer="Emergent in Flan-T5 relative to T5-large on open instructions.",
         research="Not guaranteed for letter-level unnatural tasks (pig latin).",
         notebook_file="04_seq2seq.ipynb", cell_index=28, twin_id="seq2seq-t5"),
    dict(id="c-prompt-eng", slug="prompt-engineering", name="Prompt engineering", cluster="seq2seq",
         definition="Choosing inputs (format, few-shot, iteration, priming) to get better behavior from a frozen model.",
         school="Wording the exam question so the student shows what they know.",
         engineer="Format-abiding, few-shot, trial-and-error, decoder priming.",
         research="Per-model; some cannot deviate enough for a use case.",
         notebook_file="04_seq2seq.ipynb", cell_index=28, twin_id="seq2seq-t5"),
    dict(id="c-hallucination", slug="hallucination", name="Hallucination", cluster="seq2seq",
         definition="Model emits ungrounded personal facts ('what is my name?') rather than abstaining.",
         school="Making up an answer instead of saying 'I don't know'.",
         engineer="Notebook 4 task: ask unknown personal facts; try honesty prompts.",
         research="Course does not claim a complete fix; prompting can reduce but not eliminate.",
         notebook_file="04_seq2seq.ipynb", cell_index=34, twin_id="seq2seq-t5"),
    # --- 05 ---
    dict(id="c-modality", slug="modality", name="Modality", cluster="multimodal",
         definition="Distinct sensory data type with its own rules: language (ordered tokens), images (2D pixels), audio (time series).",
         school="Eyes, ears, and words are different kinds of stuff.",
         engineer="Convolution for spatial locality; transformers for ordered sequences.",
         research="Attention is not limited to words — it is a sequence interface.",
         notebook_file="05_multimodal.ipynb", cell_index=3, twin_id="multimodal"),
    dict(id="c-whisper", slug="whisper", name="Whisper ASR", cluster="multimodal",
         definition="Audio → log-mel spectrogram windows → encoder sequence → decoder via cross-attention. whisper-base ~73M; large-v2 1.55B.",
         school="Turns sound pictures into sentences.",
         engineer="pipeline automatic-speech-recognition; base faster, large-v2 better multilingual.",
         research="Domain losses/tokenizers largely out of course scope; paper recommended.",
         notebook_file="05_multimodal.ipynb", cell_index=6, twin_id="multimodal"),
    dict(id="c-vit", slug="vision-transformer", name="Vision Transformer", cluster="multimodal",
         definition="Image patches as tokens (An Image is Worth 16x16 Words).",
         school="Cut the photo into stamps, read the stamps like words.",
         engineer="Pairs with a language decoder for captioning.",
         research="nlpconnect/vit-gpt2-image-captioning: top-downloaded but course finds it simplistic.",
         notebook_file="05_multimodal.ipynb", cell_index=18, twin_id="multimodal"),
    dict(id="c-blip", slug="blip", name="BLIP captioning", cluster="multimodal",
         definition="Salesforce BLIP: stronger captioning; two encoder layers + specialized pretraining; supports conditional prefixes.",
         school="A better photo-describer that can start with 'I love cats'.",
         engineer="Salesforce/blip-image-captioning-large; BlipProcessor + BlipForConditionalGeneration.",
         research="Used again in assessment for image links.",
         notebook_file="05_multimodal.ipynb", cell_index=25, twin_id="multimodal"),
    dict(id="c-clip", slug="clip", name="CLIP", cluster="multimodal",
         definition="Contrastive language-image pretraining: dual encoders, related pairs agree in embedding space.",
         school="Train a picture brain and a sentence brain to point at the same idea.",
         engineer="openai/clip-vit-base-patch32; get_text_features / get_image_features; softmax similarity.",
         research="Enables retrieval, text-conditioning, and zero-shot image classification.",
         notebook_file="05_multimodal.ipynb", cell_index=35, twin_id="multimodal"),
    # --- 06 ---
    dict(id="c-decoder-only", slug="decoder-only", name="Decoder-only models", cluster="decoder",
         definition="Drop the encoder when context and generation share a vocabulary; feed the passage into the decoder (GPT family).",
         school="One writer that both reads the prompt and continues it.",
         engineer="Loses bidirectional cross-attention supervision; anything in the input can be a command.",
         research="GPT-2 insufficient for unrestricted NLG in the course's judgment.",
         notebook_file="06_textgen.ipynb", cell_index=3, twin_id="decoder-sampling"),
    dict(id="c-codegen", slug="codegen", name="CodeGen", cluster="decoder",
         definition="Salesforce decoder trained on BigPython; tokenizer more granular; 350M-mono used for fibonacci completion.",
         school="An autocomplete for Python that sometimes writes extra junk.",
         engineer="Overgenerate, misinterpret, assume externals, go off track.",
         research="Larger CodeGen 2.5 7B not loaded (compute). Copilot is a multi-model API, not one LLM.",
         notebook_file="06_textgen.ipynb", cell_index=16, twin_id="decoder-sampling"),
    dict(id="c-llama2", slug="llama-2-chat", name="Llama-2 chat", cluster="decoder",
         definition="Open Meta chat models 7B/13B/70B; course uses TheBloke GPTQ. Chat format <s>[INST]<<SYS>>.",
         school="A talkative open model you can run yourself if you shrink it.",
         engineer="Must use the fine-tuned template; raw completion is the wrong interface.",
         research="SFT + human-feedback ranking; ChatGPT internals are not accessible — contrast.",
         notebook_file="06_textgen.ipynb", cell_index=25, twin_id="decoder-sampling"),
    dict(id="c-quant", slug="quantization", name="Quantization", cluster="decoder",
         definition="Map high-precision weights to a smaller numeric set to save memory/compute, usually shifting quality.",
         school="Write the recipe with fewer decimal places so it fits in a smaller notebook.",
         engineer="bitsandbytes load_in_8bit/4bit vs GPTQ (needs unquantized forward; AutoGPTQ/Optimum).",
         research="70B ~135GB; int8 ~69GB and conversion retains original; A100 vs A10/T4 notes.",
         notebook_file="06_textgen.ipynb", cell_index=19, twin_id="quantization-memory"),
    dict(id="c-sft", slug="instruction-finetuning", name="Instruction / SFT", cluster="decoder",
         definition="Fine-tune on formatted synthetic dialog so the model respects roles and templates.",
         school="Practice tests that always use the same worksheet layout.",
         engineer="Llama-2 chat SFT then reward-model ranking.",
         research="Generation priming, few-shot, eos_token_id used to constrain outputs in tasks.",
         notebook_file="06_textgen.ipynb", cell_index=26, twin_id="decoder-sampling"),
    # --- 07 ---
    dict(id="c-orchestrate", slug="llm-orchestration", name="LLM orchestration", cluster="stateful",
         definition="Libraries that organize one or more LLMs to solve real tasks: chat, planning, API calls.",
         school="A stage manager for the actor (the LLM).",
         engineer="LangChain is the course's example; originally GPT-API-centric.",
         research="Local models may not match default chain assumptions.",
         notebook_file="07_stateful_models.ipynb", cell_index=4, twin_id="langchain-memory"),
    dict(id="c-chain", slug="langchain-chain", name="LangChain Chain", cluster="stateful",
         definition="Dict-in dict-out module composable like nn.Module; TransformChain, SequentialChain, LLMChain.",
         school="LEGO blocks that pass dictionaries instead of tensors.",
         engineer="LLMChain = prompt + LLM with preprocess/postprocess mental model.",
         research="_call / _acall customization points in source.",
         notebook_file="07_stateful_models.ipynb", cell_index=7, twin_id="langchain-memory"),
    dict(id="c-memory", slug="conversation-memory", name="Conversation memory", cluster="stateful",
         definition="State injected as history; buffer, summary, KG, vector retriever variants.",
         school="A notepad so the bot remembers your name.",
         engineer="ConversationChain + ConversationBuffer; partials gotcha with input_variables.",
         research="Context limit forces lossy summaries; faithfulness vs length tradeoff.",
         notebook_file="07_stateful_models.ipynb", cell_index=27, twin_id="langchain-memory"),
    dict(id="c-rag", slug="rag", name="Retrieval-augmented generation", cluster="stateful",
         definition="Augment generation with retrieved environment text (e.g. vector similarity lookup).",
         school="Open the textbook, then answer.",
         engineer="Always-on retrieval vs agent-chosen tools.",
         research="LlamaIndex deferred to extras / later courses.",
         notebook_file="07_stateful_models.ipynb", cell_index=39, twin_id="rag-agent"),
    dict(id="c-agent", slug="llm-agent", name="Agent", cluster="stateful",
         definition="LLM system(s) in an event loop using tools until stop; ReAct/MRKL inspiration.",
         school="Think, use a tool, look, repeat, then answer.",
         engineer="ZeroShotAgent / initialize_agent zero-shot-react-description; scratchpad.",
         research="Precise: event loop accumulating context. Dialog-spanning loop = assessment.",
         notebook_file="07_stateful_models.ipynb", cell_index=39, twin_id="rag-agent"),
    dict(id="c-tools", slug="agent-tools", name="Tools", cluster="stateful",
         definition="Utilities with name, description, func; AutoTool recipe; Python REPL is powerful and dangerous.",
         school="Buttons the agent is allowed to press.",
         engineer="Ask-For-Input Tool wraps the user. exec() REPL is demo-only.",
         research="Course warns general Python access is a bad idea in practice.",
         notebook_file="07_stateful_models.ipynb", cell_index=43, twin_id="rag-agent"),
    dict(id="c-react", slug="react-mrkl", name="ReAct / MRKL", cluster="stateful",
         definition="Reasoning + Acting; Modular Reasoning, Knowledge and Language — endow options and let the model choose steps.",
         school="Think out loud, then act, then think again.",
         engineer="Prompt format Thought/Action/Action-Input/Observation/Final Answer.",
         research="Works better with examples or finetuning; Llama-2 may fail the default template.",
         notebook_file="07_stateful_models.ipynb", cell_index=44, twin_id="rag-agent"),
    # --- 08 ---
    dict(id="c-assess", slug="assessment-agent", name="Assessment custom agent", cluster="assessment",
         definition="MyAgent on BaseSingleActionAgent; pass ≥3/5: memory, image, code fences, toxicity, emotion.",
         school="Build a chatbot that remembers you, can look at a picture, and notices mood.",
         engineer="plan() uses intermediate_steps; Ask-For-Input Tool; SetParams for gen kwargs.",
         research="ToxicityModel returns reward = 1 - toxicity. Assessment script uses 13B GPTQ.",
         notebook_file="08_assessment.ipynb", cell_index=22, twin_id="assessment-agent"),
    dict(id="c-toxicity-reward", slug="toxicity-reward", name="Inverted toxicity reward", cluster="assessment",
         definition="nicholasKluge/ToxicityModel returns reward where reward = 1 - toxicity.",
         school="A high score means nicer text, not more toxic.",
         engineer="Do not treat the raw logit as toxicity without inversion.",
         research="Useful for guardrails / human handoff — course lists product uses.",
         notebook_file="08_assessment.ipynb", cell_index=23, twin_id="assessment-agent"),
    # --- extra graph (~100 total) ---
    dict(id="c-fillmask", slug="fill-mask-task", name="Fill-mask task", cluster="fundamentals",
         definition="Predict a vocabulary token at a [MASK] position; the first pipeline the course peels apart.",
         school="Cover a word, guess the word from the rest of the sentence.",
         engineer="FillMaskPipeline scores the masked index over the vocab.",
         research="Still extractive over a closed vocab — not free generation.",
         analogy="A fill-in-the-blank homework sheet.",
         notebook_file="01_llm_intro.ipynb", cell_index=9, twin_id="pipeline-flow"),
    dict(id="c-preprocess", slug="pipeline-preprocess", name="Pipeline preprocess", cluster="fundamentals",
         definition="Tokenizer stage that turns a string into model tensors before forward.",
         school="The waiter writing the kitchen ticket.",
         engineer="tokenizer(text, return_tensors=pt) inside preprocess.",
         research="The place hidden tensors first appear if you subclass the pipeline.",
         analogy="Writing an order ticket the kitchen can read.",
         notebook_file="01_llm_intro.ipynb", cell_index=14, twin_id="pipeline-flow"),
    dict(id="c-forward", slug="pipeline-forward", name="Pipeline forward", cluster="fundamentals",
         definition="Model tensor-to-tensor pass inside a HuggingFace pipeline.",
         school="The kitchen cooking from the ticket.",
         engineer="model(**inputs) or pipeline._forward.",
         research="This is where GPU RAM must hold weights.",
         analogy="The stove, not the waiter.",
         notebook_file="01_llm_intro.ipynb", cell_index=14, twin_id="pipeline-flow"),
    dict(id="c-postprocess", slug="pipeline-postprocess", name="Pipeline postprocess", cluster="fundamentals",
         definition="Task-specific conversion of tensors back to human-readable output.",
         school="Plating the food so a person can eat it.",
         engineer="Decode top tokens, attach scores, format dicts.",
         research="Postprocess is not the model; swapping it changes the product, not the weights.",
         analogy="Putting the meal on a plate.",
         notebook_file="01_llm_intro.ipynb", cell_index=14, twin_id="pipeline-flow"),
    dict(id="c-never-exec", slug="never-execute", name="Notebooks as data", cluster="fundamentals",
         definition="This academy treats notebook cells as ingested text. It never runs them.",
         school="You read the recipe. The kitchen here is closed.",
         engineer="blocked_execution=True; flags for ! and %%bash.",
         research="Safety: course cells can include nvidia-smi and other host commands.",
         analogy="A cookbook you do not cook from in the library.",
         notebook_file="01_llm_intro.ipynb", cell_index=17, twin_id="incident-diagnosis"),
    dict(id="c-cls-sep", slug="cls-sep", name="CLS and SEP tokens", cluster="intake",
         definition="Special tokens BERT adds; the course sometimes strips them for embedding illustrations.",
         school="Bookends the model staples onto a sentence.",
         engineer="encode adds [CLS]…[SEP]; illustration code may drop them.",
         research="Pooled sequence class often reads index 0 (CLS).",
         analogy="A title page and a period the model added.",
         notebook_file="02_llm_intake.ipynb", cell_index=12, twin_id="tokenizer-embeddings"),
    dict(id="c-vocab", slug="bert-vocab", name="BERT vocabulary size", cluster="intake",
         definition="bert-base-uncased uses 30,522 token classes in this course.",
         school="About thirty thousand brick types.",
         engineer="Embedding(30522, 768).",
         research="Closed set: MLM cannot invent an ID outside this table.",
         analogy="A box of 30,522 labeled bricks.",
         notebook_file="02_llm_intake.ipynb", cell_index=10, twin_id="tokenizer-embeddings"),
    dict(id="c-hidden", slug="hidden-size-768", name="Hidden size 768", cluster="intake",
         definition="BERT-base residual stream width used throughout notebooks 1–3.",
         school="Each brick’s personality is a list of 768 numbers.",
         engineer="d_model=768; heads 12×64.",
         research="Concatenating three embeddings to 2304 is the classic bug.",
         analogy="A 768-slot scorecard, not three scorecards taped together.",
         notebook_file="02_llm_intake.ipynb", cell_index=10, twin_id="tokenizer-embeddings"),
    dict(id="c-layernorm", slug="embedding-layernorm", name="Embedding LayerNorm", cluster="intake",
         definition="After word+pos+type addition, BERT LayerNorms the sum.",
         school="Stir the three flavors, then even out the taste.",
         engineer="embeddings forward: add then LayerNorm + dropout.",
         research="Norm is why the sum stays a well-behaved 768-d vector.",
         analogy="Stirring then tasting so no flavor dominates.",
         notebook_file="02_llm_intake.ipynb", cell_index=21, twin_id="tokenizer-embeddings"),
    dict(id="c-scaled-dot", slug="scaled-dot-product", name="Scaled dot-product attention", cluster="attention",
         definition="Softmax(QK^T / √d_k) V as presented for encoder self-attention.",
         school="Compare questions to keys, then mix the values.",
         engineer="d_k=64 for BERT-base heads; scale prevents huge logits.",
         research="The course uses this as the prelude from cosine similarity.",
         analogy="Who in the room answers my question, then borrow their notes.",
         notebook_file="02_llm_intake.ipynb", cell_index=27, twin_id="attention-encoder"),
    dict(id="c-qk-v", slug="qkv-projections", name="Q, K, V projections", cluster="attention",
         definition="Linear maps from the residual stream into query, key, and value.",
         school="Three different nametags for the same person.",
         engineer="W_q, W_k, W_v; same sequence for self-attention.",
         research="Cross-attention later takes K,V from another sequence.",
         analogy="The same student as asker, index card, and answer sheet.",
         notebook_file="02_llm_intake.ipynb", cell_index=27, twin_id="attention-encoder"),
    dict(id="c-ffn", slug="encoder-ffn", name="Encoder feed-forward", cluster="attention",
         definition="Per-token MLP 768 → 3072 → 768 inside each encoder block.",
         school="After looking around, each brick thinks alone.",
         engineer="Intermediate size 3072 in BERT-base.",
         research="Position-wise; does not mix tokens (attention already did).",
         analogy="Private homework after group discussion.",
         notebook_file="02_llm_intake.ipynb", cell_index=27, twin_id="attention-encoder"),
    dict(id="c-padding", slug="padding-mask", name="Padding mask", cluster="attention",
         definition="Attention mask used so pad tokens do not look like real words.",
         school="Ignore the blank seats at the end of the row.",
         engineer="additive -inf on pad positions.",
         research="Different from token_type_ids and from causal masks.",
         analogy="Empty chairs do not get a vote.",
         notebook_file="02_llm_intake.ipynb", cell_index=6, twin_id="attention-encoder"),
    dict(id="c-squad", slug="squad-extractive", name="SQuAD-style extractive QA", cluster="encoder-tasks",
         definition="Answer is a span of the context; modeled with start and end logits.",
         school="Highlight the sentence that already has the answer.",
         engineer="deepset/roberta-base-squad2 pipeline.",
         research="If the fact is not in the paragraph, a good extractive head should fail closed.",
         analogy="Open-book quiz: the answer is on the page.",
         notebook_file="03_encoder_task.ipynb", cell_index=8, twin_id="encoder-heads"),
    dict(id="c-start-end", slug="start-end-logits", name="Start and end logits", cluster="encoder-tasks",
         definition="Two scores per context token: begin-answer and end-answer.",
         school="Mark the first and last word of the highlight.",
         engineer="Output shape [seq, 2] or two [seq] heads.",
         research="Argmax start/end must be a valid ordered span.",
         analogy="Drawing brackets around a quote.",
         notebook_file="03_encoder_task.ipynb", cell_index=8, twin_id="encoder-heads"),
    dict(id="c-go-emotions", slug="go-emotions", name="GoEmotions sequence class", cluster="encoder-tasks",
         definition="SamLowe/roberta-base-go_emotions: 28 emotion labels from a pooled position.",
         school="Read the whole note, name the feeling.",
         engineer="pipeline sentiment-analysis with that checkpoint.",
         research="n→1, not a label per token.",
         analogy="A mood stamp on the whole postcard.",
         notebook_file="03_encoder_task.ipynb", cell_index=12, twin_id="encoder-heads"),
    dict(id="c-mnli", slug="bart-mnli", name="BART MNLI zero-shot", cluster="encoder-tasks",
         definition="facebook/bart-large-mnli used as a multi-query entailment classifier.",
         school="Ask “does this text mean label X?” once per label.",
         engineer="One forward per candidate class.",
         research="Zero-shot here means labels were not fixed at train time, not random weights.",
         analogy="Showing the same essay to a judge with a new question each time.",
         notebook_file="03_encoder_task.ipynb", cell_index=23, twin_id="encoder-heads"),
    dict(id="c-novel-tokens", slug="novel-tokens", name="Novel token generation", cluster="seq2seq",
         definition="Ability to emit tokens that are not a substring of the input.",
         school="Writing a new sentence, not circling an old one.",
         engineer="Requires a decoder (or a closed vocab head that still picks unused words).",
         research="Encoder QA cannot invent facts missing from context.",
         analogy="Writing a reply vs highlighting a quote.",
         notebook_file="04_seq2seq.ipynb", cell_index=4, twin_id="seq2seq-t5"),
    dict(id="c-pkv", slug="past-key-values", name="past_key_values", cluster="seq2seq",
         definition="Cached K/V that grow as the decoder emits tokens.",
         school="The writer’s scrap notes that get longer each word.",
         engineer="Grows with output steps; encoder context stays.",
         research="This is why decoder-many is not free compute.",
         analogy="A growing stack of index cards on the desk.",
         notebook_file="04_seq2seq.ipynb", cell_index=18, twin_id="seq2seq-t5"),
    dict(id="c-t5-prefix", slug="t5-prefixes", name="T5 homework prefixes", cluster="seq2seq",
         definition="Vanilla T5 was trained on short task prefixes, not open chat.",
         school="It expects “translate English to French:” not “hey, what’s up?”.",
         engineer="text2text-generation with prefixes.",
         research="Scale alone does not make T5 a chatbot; Flan changes the recipe.",
         analogy="A student who only practiced labeled worksheets.",
         notebook_file="04_seq2seq.ipynb", cell_index=14, twin_id="seq2seq-t5"),
    dict(id="c-pig-latin", slug="pig-latin-fail", name="Expected Pig Latin fail", cluster="seq2seq",
         definition="Course claim: Pig Latin is expected to fail from tokenization and semantics.",
         school="A silly word game the model was not taught.",
         engineer="Do not treat failure as a GPU bug.",
         research="Tokenization splits the joke; the task is not in the prefix set.",
         analogy="Asking a French worksheet kid to speak pig latin.",
         notebook_file="04_seq2seq.ipynb", cell_index=30, twin_id="seq2seq-t5"),
    dict(id="c-pad-start", slug="decoder-pad-start", name="Decoder start from pad", cluster="seq2seq",
         definition="Notebook 4: first decoder step often starts from <pad> and stops at </s>.",
         school="The writer starts from a blank stamp, then stops at the end mark.",
         engineer="decoder_start_token_id often pad for T5.",
         research="Not the same as GPT bos/eos conventions.",
         analogy="Starting a letter from a blank stamp.",
         notebook_file="04_seq2seq.ipynb", cell_index=18, twin_id="seq2seq-t5"),
    dict(id="c-spectrogram", slug="whisper-spectrogram", name="Whisper spectrogram", cluster="multimodal",
         definition="Audio is windowed into a frequency picture before it becomes a token sequence.",
         school="A comic strip of sound frequencies.",
         engineer="~50 frames/sec qualitative in the twin; then encoder tokens.",
         research="If it is a sequence, cross-attention can condition text.",
         analogy="Turning a song into a flip-book of frequencies.",
         notebook_file="05_multimodal.ipynb", cell_index=9, twin_id="multimodal"),
    dict(id="c-patches", slug="vit-patches", name="ViT image patches", cluster="multimodal",
         definition="An image is cut into 16×16 patches that behave like tokens.",
         school="Tiles on a floor become words.",
         engineer="Patch embedding + encoder; paper title is the teaching hook.",
         research="Same sequence interface as text for a decoder.",
         analogy="Cutting a photo into postage stamps.",
         notebook_file="05_multimodal.ipynb", cell_index=23, twin_id="multimodal"),
    dict(id="c-vit-gpt2", slug="vit-gpt2-caption", name="ViT-GPT2 captioning", cluster="multimodal",
         definition="nlpconnect/vit-gpt2-image-captioning: weaker qualitative captions than BLIP in the course story.",
         school="A simple camera that writes a short sentence.",
         engineer="image-to-text pipeline.",
         research="Generation, not CLIP retrieval.",
         analogy="A cheap postcard writer.",
         notebook_file="05_multimodal.ipynb", cell_index=23, twin_id="multimodal"),
    dict(id="c-dual-enc", slug="clip-dual-encoder", name="CLIP dual encoders", cluster="multimodal",
         definition="Separate image and text towers trained so related embeddings agree.",
         school="Two libraries that point at the same idea.",
         engineer="get_image_features / get_text_features + similarity.",
         research="Softmax over candidates is retrieval or class, not a caption.",
         analogy="Two card catalogs that share a call number.",
         notebook_file="05_multimodal.ipynb", cell_index=36, twin_id="multimodal"),
    dict(id="c-temp", slug="sampling-temperature", name="Sampling temperature", cluster="decoder",
         definition="Softmax temperature: higher is more adventurous, lower is peakier.",
         school="How wild the dice are.",
         engineer="logits / temperature before softmax; do_sample must be on.",
         research="Qualitative diversity/coherence trade — not a GPU measurement here.",
         analogy="Spicy vs mild dice.",
         notebook_file="06_textgen.ipynb", cell_index=6, twin_id="decoder-sampling"),
    dict(id="c-do-sample", slug="do-sample", name="do_sample vs greedy", cluster="decoder",
         definition="Greedy decode picks the top token; sampling draws from the distribution.",
         school="Always the favorite word vs rolling among good words.",
         engineer="do_sample=False → deterministic given ties.",
         research="CodeGen failure modes are about training files, not only temperature.",
         analogy="Always pizza vs spinning a food wheel.",
         notebook_file="06_textgen.ipynb", cell_index=6, twin_id="decoder-sampling"),
    dict(id="c-causal", slug="causal-mask", name="Causal mask", cluster="decoder",
         definition="Decoder-only models may not attend to future tokens.",
         school="You may only look at words already written.",
         engineer="Triangular attention mask.",
         research="Different job from BERT padding masks.",
         analogy="No peeking at the next page.",
         notebook_file="06_textgen.ipynb", cell_index=3, twin_id="decoder-sampling"),
    dict(id="c-inst-sys", slug="llama2-inst-sys", name="Llama-2 INST/SYS template", cluster="decoder",
         definition="Chat-tuned Llama-2 expects <s>[INST]<<SYS>>… formatting.",
         school="A formal letter, not a sticky note.",
         engineer="Apply the fine-tune template or the model misbehaves.",
         research="Raw completion on a chat checkpoint is misuse.",
         analogy="Addressing the envelope the way the clerk was trained.",
         notebook_file="06_textgen.ipynb", cell_index=31, twin_id="decoder-sampling"),
    dict(id="c-gptq", slug="gptq", name="GPTQ quantization", cluster="decoder",
         definition="Adaptive rounding using representative inputs; needs an unquantized forward to produce.",
         school="Packing the suitcase using a practice load, then throwing the practice load away.",
         engineer="TheBloke GPTQ checkpoints skip self-quantization.",
         research="Peak RAM during self-quant can be ~2× the final footprint.",
         analogy="Trying on clothes, then shipping only the packed bag.",
         notebook_file="06_textgen.ipynb", cell_index=19, twin_id="quantization-memory"),
    dict(id="c-bnb", slug="bitsandbytes", name="bitsandbytes quantization", cluster="decoder",
         definition="On-the-fly 8-bit (and related) loading path contrasted with GPTQ in the course.",
         school="Shrink the suitcase as you unpack it.",
         engineer="load_in_8bit style APIs.",
         research="Course 70B ~135GB FP16 vs ~69GB 8-bit story.",
         analogy="Vacuum bags you seal at the door.",
         notebook_file="06_textgen.ipynb", cell_index=19, twin_id="quantization-memory"),
    dict(id="c-thebloke", slug="thebloke-gptq", name="TheBloke GPTQ checkpoints", cluster="decoder",
         definition="Prequantized Hub checkpoints the course uses so learners skip self-quantization.",
         school="Someone else already packed the small suitcase.",
         engineer="TheBloke/Llama-2-13B-chat-GPTQ for assessment.",
         research="13B 4-qt is the grader assumption, not 70B.",
         analogy="Buying a packed travel bag instead of packing 70 shirts yourself.",
         notebook_file="06_textgen.ipynb", cell_index=20, twin_id="quantization-memory"),
    dict(id="c-70b-ram", slug="llama-70b-ram", name="70B FP16 memory story", cluster="decoder",
         definition="Course qualitative number: 70B ≈ 135GB in FP16.",
         school="A data-center suitcase, not a laptop backpack.",
         engineer="params × bytes/param; not a twin measurement.",
         research="Cite as COURSE_SOURCE / EXPECTED_RESULT, never ACTUAL_RUN from a slider.",
         analogy="A moving truck, not a backpack.",
         notebook_file="06_textgen.ipynb", cell_index=19, twin_id="quantization-memory"),
    dict(id="c-llmchain", slug="llmchain", name="LLMChain", cluster="stateful",
         definition="Stateless LangChain wrapper: one prompt in, one completion out, no memory.",
         school="A stranger every phone call.",
         engineer="No history unless you inject it.",
         research="ConversationChain is the memory-aware cousin.",
         analogy="A help desk that hangs up and forgets.",
         notebook_file="07_stateful_models.ipynb", cell_index=26, twin_id="langchain-memory"),
    dict(id="c-buffer-mem", slug="conversation-buffer", name="Conversation buffer memory", cluster="stateful",
         definition="Stores raw turns and injects them into the next prompt.",
         school="A notepad that keeps every line.",
         engineer="grows linearly with turns; can overflow context.",
         research="Faithful but not free.",
         analogy="Keeping every text message.",
         notebook_file="07_stateful_models.ipynb", cell_index=28, twin_id="langchain-memory"),
    dict(id="c-summary-mem", slug="summary-memory", name="Summary memory", cluster="stateful",
         definition="Compresses history; lossy on purpose.",
         school="A diary that only keeps the gist.",
         engineer="stored tokens grow slowly; facts can vanish.",
         research="Summary-buffer is the hybrid.",
         analogy="Telling a friend “we talked about lunch” instead of quoting.",
         notebook_file="07_stateful_models.ipynb", cell_index=28, twin_id="langchain-memory"),
    dict(id="c-history-var", slug="history-input-variable", name="history in input_variables", cluster="stateful",
         definition="ConversationChain may not see PromptTemplate partials; history must be an input variable.",
         school="The notepad only works if the form has a “history” blank.",
         engineer="Put history in input_variables.",
         research="Classic notebook 7 gotcha.",
         analogy="A form missing the notes field.",
         notebook_file="07_stateful_models.ipynb", cell_index=28, twin_id="langchain-memory"),
    dict(id="c-vector-mem", slug="vectorstore-memory", name="VectorStore memory", cluster="stateful",
         definition="Retrieve prior text into the prompt; RAG-like, not automatically an agent loop.",
         school="Looking up an old page and pasting it.",
         engineer="VectorStoreRetrieverMemory.",
         research="Retrieval ≠ ReAct.",
         analogy="Pulling a file from a cabinet.",
         notebook_file="07_stateful_models.ipynb", cell_index=39, twin_id="rag-agent"),
    dict(id="c-ask-input", slug="ask-for-input-tool", name="Ask-For-Input Tool", cluster="stateful",
         definition="Tool that treats the user as the next action; the assessment dialog loop.",
         school="The intern turns and asks you a question.",
         engineer="Preferred over Python REPL.",
         research="User-as-tool is the assessment event loop.",
         analogy="Asking the customer instead of breaking into the stockroom.",
         notebook_file="07_stateful_models.ipynb", cell_index=45, twin_id="rag-agent"),
    dict(id="c-repl", slug="python-repl-tool", name="Python REPL tool", cluster="stateful",
         definition="Course-flagged dangerous tool: arbitrary code execution.",
         school="Handing the intern a live workshop with power tools.",
         engineer="Do not default this into a product agent.",
         research="Security risk + incident twin ground truth.",
         analogy="Keys to the whole building.",
         notebook_file="07_stateful_models.ipynb", cell_index=43, twin_id="incident-diagnosis"),
    dict(id="c-scratchpad", slug="agent-scratchpad", name="Agent scratchpad", cluster="stateful",
         definition="Growing Thought/Action/Observation trace inside a ReAct loop.",
         school="The intern’s messy notebook of tries.",
         engineer="intermediate_steps feed the next plan().",
         research="Grows until Final Answer or a stop.",
         analogy="Scratch paper that gets longer each attempt.",
         notebook_file="07_stateful_models.ipynb", cell_index=45, twin_id="rag-agent"),
    dict(id="c-react-loop", slug="behind-the-scenes-loop", name="Behind-the-scenes vs dialog loop", cluster="stateful",
         definition="Notebook 7: some agents loop internally; assessment talks to the user each turn.",
         school="Thinking in the back room vs asking you out loud.",
         engineer="loop=behind_the_scenes vs dialog.",
         research="Assessment requires the dialog style.",
         analogy="A chef who never leaves the kitchen vs one who asks how salty you want it.",
         notebook_file="07_stateful_models.ipynb", cell_index=39, twin_id="rag-agent"),
    dict(id="c-blip-assess", slug="blip-assessment", name="BLIP image feature", cluster="assessment",
         definition="Assessment image path in backticks captions with BLIP-large.",
         school="If they paste a picture path, describe the picture.",
         engineer="Salesforce/blip-image-captioning-large; trigger `path/to/img.png`.",
         research="One of five features; need ≥3.",
         analogy="Looking at a photo the customer slid across the counter.",
         notebook_file="08_assessment.ipynb", cell_index=22, twin_id="assessment-agent"),
    dict(id="c-code-fence", slug="code-fence-feature", name="Code-fence feature", cluster="assessment",
         definition="Triple backtick in the user message triggers code generation without emitting fences.",
         school="If they show a code box, write code back — no extra box lines.",
         engineer="Trigger ``` ; do not echo fences.",
         research="Feature 3/5.",
         analogy="Seeing a sketch and drawing a cleaner one.",
         notebook_file="08_assessment.ipynb", cell_index=22, twin_id="assessment-agent"),
    dict(id="c-13b-grader", slug="grader-13b", name="13B GPTQ grader", cluster="assessment",
         definition="Assessment harness assumes TheBloke Llama-2-13B-chat-GPTQ, not 70B.",
         school="The exam uses the smaller packed model.",
         engineer="Match the grader checkpoint.",
         research="Building against 70B is a business miss.",
         analogy="Studying the wrong textbook edition.",
         notebook_file="08_assessment.ipynb", cell_index=8, twin_id="assessment-agent"),
    dict(id="c-setparams", slug="setparams", name="SetParams context manager", cluster="assessment",
         definition="Helper to tweak pipeline _forward_params without leaking a full solution.",
         school="A knob box for generation settings.",
         engineer="class SetParams around pipeline calls.",
         research="Limit generation; preload HF models.",
         analogy="A volume knob on the stereo, not a new stereo.",
         notebook_file="08_assessment.ipynb", cell_index=9, twin_id="assessment-agent"),
    dict(id="c-evidence", slug="evidence-types", name="Six evidence types", cluster="fundamentals",
         definition="COURSE_SOURCE, EXPECTED_RESULT, SIMULATED_RESULT, ACTUAL_RUN, TUTOR_INTERPRETATION, EXTERNAL_RESEARCH.",
         school="Every number wears one name tag.",
         engineer="Twins cannot emit ACTUAL_RUN; imports can.",
         research="Type system plus tests enforce the split.",
         analogy="Six different stamps on a document.",
         notebook_file="01_llm_intro.ipynb", cell_index=14, twin_id="risk-radar"),
    dict(id="c-sim-vs-run", slug="sim-vs-actual", name="Simulation vs actual run", cluster="fundamentals",
         definition="Web sliders are educational simulations. GPU measurements must be imported.",
         school="A flight simulator is not the airplane’s black box.",
         engineer="evidence_type stays SIMULATED_RESULT in the twin engine.",
         research="Citing a twin as TPOT is a business risk.",
         analogy="A board-game bank is not the real bank.",
         notebook_file="01_llm_intro.ipynb", cell_index=17, twin_id="risk-radar"),
    dict(id="c-license-gap", slug="missing-license-appendix", name="Missing license extras", cluster="fundamentals",
         definition="extras_and_licenses is not in this repo; do not invent it.",
         school="The legal appendix is missing from the box.",
         engineer="Bring your own license files.",
         research="Personal-use DLI materials; not NVIDIA-endorsed software.",
         analogy="A textbook without the copyright page — do not write one.",
         notebook_file="01_llm_intro.ipynb", cell_index=8, twin_id="risk-radar"),
    dict(id="c-incident", slug="incident-diagnosis", name="Commit-then-reveal diagnosis", cluster="stateful",
         definition="Name the cause before the twin shows ground truth.",
         school="Guess, then lock, then see the answer key.",
         engineer="committed=false withholds ground_truth.",
         research="Active learning: predict before observe.",
         analogy="Sealed envelope until you write your guess.",
         notebook_file="07_stateful_models.ipynb", cell_index=26, twin_id="incident-diagnosis"),
]

EDGES: list[tuple[str, str, str]] = [
    ("c-hf", "c-transformers", "DEPENDS_ON"),
    ("c-transformers", "c-pipeline", "IMPLEMENTED_IN"),
    ("c-pipeline", "c-tokenizer", "PART_OF"),
    ("c-pipeline", "c-bert-base", "IMPLEMENTED_IN"),
    ("c-tokenizer", "c-token", "PART_OF"),
    ("c-token", "c-input-ids", "IMPLEMENTED_IN"),
    ("c-input-ids", "c-word-emb", "DEPENDS_ON"),
    ("c-pos-emb", "c-emb-add", "PART_OF"),
    ("c-word-emb", "c-emb-add", "PART_OF"),
    ("c-token-type", "c-emb-add", "PART_OF"),
    ("c-emb-add", "c-attention", "PREREQUISITE_OF"),
    ("c-attention", "c-mha", "PART_OF"),
    ("c-attention", "c-encoder", "PART_OF"),
    ("c-residual", "c-encoder", "OPTIMIZES"),
    ("c-encoder", "c-mlm", "PREREQUISITE_OF"),
    ("c-mlm", "c-token-cls", "PART_OF"),
    ("c-encoder", "c-qa-span", "PREREQUISITE_OF"),
    ("c-encoder", "c-seq-cls", "PREREQUISITE_OF"),
    ("c-nsp", "c-seq-cls", "OPTIMIZES"),
    ("c-seq-cls", "c-zeroshot", "COMPARES_WITH"),
    ("c-zeroshot", "c-seq2seq", "PREREQUISITE_OF"),
    ("c-encoder", "c-seq2seq", "COMPARES_WITH"),
    ("c-decoder", "c-seq2seq", "PART_OF"),
    ("c-cross-attn", "c-t5", "PART_OF"),
    ("c-t5", "c-flan", "PREREQUISITE_OF"),
    ("c-flan", "c-icl", "INCREASES"),
    ("c-icl", "c-prompt-eng", "IMPLEMENTED_IN"),
    ("c-cross-attn", "c-whisper", "IMPLEMENTED_IN"),
    ("c-cross-attn", "c-vit", "IMPLEMENTED_IN"),
    ("c-vit", "c-blip", "COMPARES_WITH"),
    ("c-clip", "c-blip", "OPTIMIZES"),
    ("c-decoder", "c-decoder-only", "PART_OF"),
    ("c-decoder-only", "c-codegen", "IMPLEMENTED_IN"),
    ("c-decoder-only", "c-llama2", "IMPLEMENTED_IN"),
    ("c-quant", "c-llama2", "OPTIMIZES"),
    ("c-sft", "c-llama2", "OPTIMIZES"),
    ("c-llama2", "c-orchestrate", "PREREQUISITE_OF"),
    ("c-orchestrate", "c-chain", "IMPLEMENTED_IN"),
    ("c-chain", "c-memory", "PART_OF"),
    ("c-memory", "c-rag", "COMPARES_WITH"),
    ("c-rag", "c-agent", "COMPARES_WITH"),
    ("c-agent", "c-tools", "DEPENDS_ON"),
    ("c-react", "c-agent", "IMPLEMENTED_IN"),
    ("c-agent", "c-assess", "PREREQUISITE_OF"),
    ("c-blip", "c-assess", "EVIDENCED_BY"),
    ("c-toxicity-reward", "c-assess", "PART_OF"),
    ("c-qa-span", "c-seq-cls", "COMPARES_WITH"),
    ("c-t5", "c-decoder-only", "COMPARES_WITH"),
    ("c-hallucination", "c-prompt-eng", "DIAGNOSED_BY"),
    ("c-attn-mask", "c-attention", "CONTROLS"),
    ("c-pipeline", "c-preprocess", "PART_OF"),
    ("c-pipeline", "c-forward", "PART_OF"),
    ("c-pipeline", "c-postprocess", "PART_OF"),
    ("c-fillmask", "c-pipeline", "IMPLEMENTED_IN"),
    ("c-word-emb", "c-vocab", "DEPENDS_ON"),
    ("c-word-emb", "c-hidden", "DEPENDS_ON"),
    ("c-emb-add", "c-layernorm", "OPTIMIZES"),
    ("c-attention", "c-scaled-dot", "IMPLEMENTED_IN"),
    ("c-attention", "c-qk-v", "PART_OF"),
    ("c-encoder", "c-ffn", "PART_OF"),
    ("c-attn-mask", "c-padding", "PART_OF"),
    ("c-qa-span", "c-squad", "IMPLEMENTED_IN"),
    ("c-qa-span", "c-start-end", "IMPLEMENTED_IN"),
    ("c-seq-cls", "c-go-emotions", "IMPLEMENTED_IN"),
    ("c-zeroshot", "c-mnli", "IMPLEMENTED_IN"),
    ("c-decoder", "c-novel-tokens", "INCREASES"),
    ("c-t5", "c-pkv", "PART_OF"),
    ("c-t5", "c-t5-prefix", "DEPENDS_ON"),
    ("c-flan", "c-pig-latin", "DIAGNOSED_BY"),
    ("c-whisper", "c-spectrogram", "PART_OF"),
    ("c-vit", "c-patches", "PART_OF"),
    ("c-blip", "c-vit-gpt2", "COMPARES_WITH"),
    ("c-clip", "c-dual-enc", "IMPLEMENTED_IN"),
    ("c-decoder-only", "c-temp", "CONTROLS"),
    ("c-decoder-only", "c-do-sample", "CONTROLS"),
    ("c-decoder-only", "c-causal", "DEPENDS_ON"),
    ("c-llama2", "c-inst-sys", "DEPENDS_ON"),
    ("c-quant", "c-gptq", "IMPLEMENTED_IN"),
    ("c-quant", "c-bnb", "IMPLEMENTED_IN"),
    ("c-gptq", "c-thebloke", "IMPLEMENTED_IN"),
    ("c-gpu-ram", "c-70b-ram", "EVIDENCED_BY"),
    ("c-chain", "c-llmchain", "IMPLEMENTED_IN"),
    ("c-memory", "c-buffer-mem", "PART_OF"),
    ("c-memory", "c-summary-mem", "PART_OF"),
    ("c-memory", "c-history-var", "DEPENDS_ON"),
    ("c-rag", "c-vector-mem", "IMPLEMENTED_IN"),
    ("c-tools", "c-ask-input", "IMPLEMENTED_IN"),
    ("c-tools", "c-repl", "COMPARES_WITH"),
    ("c-agent", "c-scratchpad", "PART_OF"),
    ("c-agent", "c-react-loop", "COMPARES_WITH"),
    ("c-assess", "c-blip-assess", "PART_OF"),
    ("c-assess", "c-code-fence", "PART_OF"),
    ("c-assess", "c-13b-grader", "DEPENDS_ON"),
    ("c-assess", "c-setparams", "IMPLEMENTED_IN"),
    ("c-evidence", "c-sim-vs-run", "PART_OF"),
    ("c-license-gap", "c-evidence", "DIAGNOSED_BY"),
    ("c-incident", "c-repl", "DIAGNOSED_BY"),
    ("c-never-exec", "c-evidence", "PART_OF"),
    ("c-cls-sep", "c-seq-cls", "PREREQUISITE_OF"),
    ("c-pad-start", "c-t5", "PART_OF"),
]


def _fill_analogies() -> None:
    for c in CONCEPTS:
        if not c.get("analogy"):
            school = (c.get("school") or "").strip()
            first = school.split(".")[0].strip()
            c["analogy"] = first + " — like a labeled drawer in a filing cabinet." if first else "A labeled drawer in a filing cabinet."


_fill_analogies()
