MISCONCEPTIONS: list[dict] = [
    dict(id="m-pipeline-model", slug="pipeline-is-the-model", left="pipeline", right="model",
         title="Pipeline vs model",
         confusion="Thinking the HuggingFace pipeline IS the neural net.",
         distinction="Pipeline = tokenizer preprocess + model forward + task postprocess.",
         source_file="01_llm_intro.ipynb", source_cell=14,
         remediation="Draw the three boxes; name which object lives in each."),
    dict(id="m-token-word", slug="token-equals-word", left="token", right="word",
         title="Token vs word",
         confusion="Assuming every token is a whole English word.",
         distinction="Tokens may be words, punctuation, subwords, or letters.",
         source_file="02_llm_intake.ipynb", source_cell=5,
         remediation="Call tokenizer.tokenize on a string with punctuation."),
    dict(id="m-type-attn", slug="token-type-vs-attention-mask", left="token_type_ids", right="attention_mask",
         title="token_type_ids vs attention_mask",
         confusion="Using type ids as the padding mask.",
         distinction="Type ids mark sentence A/B. Attention mask blocks padding (or causality later).",
         source_file="02_llm_intake.ipynb", source_cell=6,
         remediation="Tokenize a pair vs a padded batch and print both tensors."),
    dict(id="m-concat-add", slug="concat-vs-add-embeddings", left="concatenation", right="addition",
         title="How BERT combines embeddings",
         confusion="Assuming word/pos/type vectors are concatenated to 2304-d.",
         distinction="Course + HF source: they are added in 768-d, then LayerNorm.",
         source_file="02_llm_intake.ipynb", source_cell=21,
         remediation="Check modeling_bert.py embeddings forward."),
    dict(id="m-sin-pos", slug="sinusoidal-vs-learned-pos", left="sinusoidal", right="learned",
         title="Positional encoding vs BERT positions",
         confusion="BERT uses the original Transformer sinusoids.",
         distinction="BERT learns Embedding(512, 768) indexed by arange.",
         source_file="02_llm_intake.ipynb", source_cell=19,
         remediation="Print position_embeddings weight shape."),
    dict(id="m-self-cross", slug="self-vs-cross-attention", left="self-attention", right="cross-attention",
         title="Self vs cross attention",
         confusion="Calling T5 decoder self-attention 'cross' or vice versa.",
         distinction="Self: Q,K,V same sequence. Cross: Q from decoder, K/V from encoder (m≠n ok).",
         source_file="04_seq2seq.ipynb", source_cell=12,
         remediation="Write the n×m shape argument from the notebook."),
    dict(id="m-encoder-novel", slug="encoder-generates-tokens", left="encoder", right="decoder",
         title="Encoders do not emit novel tokens",
         confusion="Expecting BERT to write new sentences like ChatGPT.",
         distinction="Encoder produces insights/latents; novel tokens need a decoder (or multi-query tricks).",
         source_file="04_seq2seq.ipynb", source_cell=2,
         remediation="List what MLM/QA/cls can output vs T5."),
    dict(id="m-qa-generate", slug="qa-is-generative", left="span-QA", right="generative-QA",
         title="Extractive vs generative QA",
         confusion="SQuAD RoBERTa can invent facts not in the context.",
         distinction="Start/end logits restrict answers to substrings.",
         source_file="03_encoder_task.ipynb", source_cell=7,
         remediation="Change context so the answer is absent — extractive should fail closed."),
    dict(id="m-cls-every-token", slug="sequence-head-on-all-tokens", left="token-head", right="sequence-head",
         title="Where sequence classification reads",
         confusion="Running the 28-emotion classifier on every token independently as the sequence label.",
         distinction="Typical recipe: take index 0 / CLS (or pooled) then dense layers.",
         source_file="03_encoder_task.ipynb", cell_index=11,
         remediation="Read RobertaClassificationHead source."),
    dict(id="m-zeroshot-untrained", slug="zero-shot-means-untrained-model", left="zero-shot", right="untrained",
         title="Zero-shot ≠ randomly initialized",
         confusion="Zero-shot means the weights are random.",
         distinction="The model is trained (e.g. MNLI); the *label set* was not fixed at train time.",
         source_file="03_encoder_task.ipynb", source_cell=19,
         remediation="Restate the notebook definitions of zero-shot vs few-shot."),
    dict(id="m-t5-chat", slug="t5-is-a-chatbot", left="T5", right="Flan-T5",
         title="T5 vs Flan-T5 instruction following",
         confusion="t5-large should chat like ChatGPT if prompted nicely.",
         distinction="Vanilla T5 memorizes a shallow task set; Flan adds instruction finetuning / ICL.",
         source_file="04_seq2seq.ipynb", source_cell=24,
         remediation="Compare the same open instruction on t5-large vs flan-t5-large (expected, not measured here)."),
    dict(id="m-bigger-fixes-t5", slug="bigger-t5-fixes-instructions", left="scale", right="instruction-tuning",
         title="Scale vs training recipe",
         confusion="t5-xxl would suddenly follow arbitrary instructions.",
         distinction="Course: larger T5 still too shallow in tasks; need a more general training routine (Flan).",
         source_file="04_seq2seq.ipynb", source_cell=24,
         remediation="Quote the notebook paragraph on t5-xl/xxl."),
    dict(id="m-encoder-each-token", slug="encoder-called-every-decode-step", left="encoder-once", right="encoder-every-step",
         title="Encoder is not rerun each token",
         confusion="T5 re-encodes the source at every decoder step.",
         distinction="Encoder once for stable context; decoder steps use past_key_values.",
         source_file="04_seq2seq.ipynb", source_cell=18,
         remediation="ForwardListener mental model: encoder 1×, decoder N×."),
    dict(id="m-whisper-eq-llm", slug="whisper-is-just-an-llm", left="ASR-encoder", right="text-LLM",
         title="Whisper intake vs a text LLM",
         confusion="Whisper is 'just Llama with audio files'.",
         distinction="Audio is windowed, spectrogrammed, then sequenced; then familiar cross-attn.",
         source_file="05_multimodal.ipynb", source_cell=5,
         remediation="List the four high-level ASR stages from the notebook."),
    dict(id="m-clip-generative", slug="clip-generates-captions", left="CLIP", right="BLIP",
         title="CLIP vs captioners",
         confusion="CLIP writes captions.",
         distinction="CLIP aligns embeddings; BLIP/ViT-GPT2 generate tokens.",
         source_file="05_multimodal.ipynb", source_cell=35,
         remediation="Name one CLIP use: retrieval or zero-shot image class."),
    dict(id="m-gpt-bidirectional", slug="gpt-is-bidirectional", left="GPT", right="BERT",
         title="Decoder-only is unidirectional",
         confusion="GPT-2 attends to future tokens like BERT.",
         distinction="Causal decoder; BERT encoder is bidirectional MLM.",
         source_file="06_textgen.ipynb", source_cell=3,
         remediation="Sketch the attention triangle vs full matrix."),
    dict(id="m-copilot-one-model", slug="copilot-is-one-llm", left="Copilot", right="multi-model-API",
         title="Copilot is not a single LLM",
         confusion="GitHub Copilot is one codegen checkpoint.",
         distinction="Course: API backed by multiple models (insert, complete, retrieve, classify).",
         source_file="06_textgen.ipynb", source_cell=11,
         remediation="List the task range named in the notebook."),
    dict(id="m-quant-always-wins", slug="quantization-always-better", left="int4", right="quality",
         title="Quantization is not free quality",
         confusion="4-bit always wins because it is newer.",
         distinction="Quality shifts; GPTQ preserves typical-use semantics better than naive rounding.",
         source_file="06_textgen.ipynb", source_cell=19,
         remediation="State a GPU/memory constraint vs a quality constraint separately."),
    dict(id="m-gptq-no-forward", slug="gptq-without-forward", left="GPTQ", right="bitsandbytes",
         title="GPTQ needs a forward pass",
         confusion="GPTQ is just casting tensors like int8 load_in_8bit.",
         distinction="GPTQ requires unquantized forwards; bitsandbytes can quantize without that.",
         source_file="06_textgen.ipynb", source_cell=19,
         remediation="Table the two HuggingFace paths from the primer."),
    dict(id="m-raw-llama-chat", slug="raw-completion-is-chat", left="completion", right="INST-template",
         title="Chat models need their template",
         confusion="Prompting Llama-2-chat like GPT-2 completion is 'using it properly'.",
         distinction="Fine-tuning enforced <s>[INST]<<SYS>>…[/INST].",
         source_file="06_textgen.ipynb", source_cell=25,
         remediation="Rewrite a user question into the official template."),
    dict(id="m-llmchain-memory", slug="llmchain-has-memory", left="LLMChain", right="ConversationChain",
         title="LLMChain is stateless",
         confusion="Calling LLMChain twice remembers the first user utterance.",
         distinction="Need ConversationChain / memory module; history variable must be fillable.",
         source_file="07_stateful_models.ipynb", source_cell=26,
         remediation="Predict the second answer with empty history."),
    dict(id="m-rag-agent", slug="rag-equals-agent", left="RAG", right="agent",
         title="RAG vs agent event loop",
         confusion="Any retrieval is an agent.",
         distinction="RAG injects retrieved text; agent is a loop that may choose tools until stop.",
         source_file="07_stateful_models.ipynb", source_cell=39,
         remediation="Classify vector memory vs ReAct scratchpad."),
    dict(id="m-repl-safe", slug="python-repl-safe", left="Python-REPL", right="restricted-tool",
         title="Python REPL is unsafe",
         confusion="Giving the agent exec() is a reasonable default.",
         distinction="Notebook: bad idea in practice; demonstration only.",
         source_file="07_stateful_models.ipynb", source_cell=43,
         remediation="Name a narrower tool that still teaches RAG."),
    dict(id="m-toxicity-sign", slug="toxicity-model-sign", left="toxicity", right="reward",
         title="ToxicityModel output sign",
         confusion="Higher ToxicityModel score means more toxic.",
         distinction="WARNING: returns reward = 1 - toxicity.",
         source_file="08_assessment.ipynb", source_cell=23,
         remediation="Convert a 0.9 reward into toxicity 0.1."),
    dict(id="m-70b-required", slug="must-use-70b", left="70B", right="13B-assessment",
         title="Assessment model size",
         confusion="The grader uses Llama-2-70B.",
         distinction="Use 13B GPTQ; 70B is optional for fun.",
         source_file="08_assessment.ipynb", source_cell=5,
         remediation="Read 8.1.1 Select Your Model."),
    dict(id="m-sim-actual", slug="simulation-vs-actual", left="SIMULATED_RESULT", right="ACTUAL_RUN",
         title="Simulation vs measured run",
         confusion="Twin numbers are GPU measurements.",
         distinction="Twins are SIMULATED_RESULT; notebooks here have no stored outputs.",
         source_file="01_llm_intro.ipynb", source_cell=9,
         remediation="Check evidence badges before citing a number."),
]

# alias for generator if cell_index used inconsistently
for m in MISCONCEPTIONS:
    if "source_cell" not in m and "cell_index" in m:
        m["source_cell"] = m["cell_index"]
    m.setdefault("source_cell", 0)
